### ISSUE TITLE
from .libs.fastdeploy_main import *DLL load failed while importing fastdeploy_main: 拒绝访问RuntimeError: FastDeploy initalized failed!

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/FastDeploy#1189]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： pip install fastdeploy-python==0.0.0 -f https://www.paddlepaddle.org.cn/whl/fastdeploy_nightly_build.html
- 【编译命令】#
- 【系统平台】:Windows 10 专业版   64 位操作系统, 基于 x64 的处理器
  - 【硬件】： Intel(R) Atom(TM) x5-Z8300  CPU @ 1.44GHz   1.44 GHz   win10平板电脑
- 【编译语言】：Python 3.8

## 问题日志及出现问题的操作流程
```

Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\fastdeploy\c_lib_wrap.py", line 164, in <module>
    from .libs.fastdeploy_main import *
ImportError: DLL load failed while importing fastdeploy_main: 拒绝访问。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "DEMOcpu.py", line 1, in <module>
    import fastdeploy as fd
  File "C:\Python38\lib\site-packages\fastdeploy\__init__.py", line 19, in <module>
    from .c_lib_wrap import (
  File "C:\Python38\lib\site-packages\fastdeploy\c_lib_wrap.py", line 166, in <module>
    raise RuntimeError("FastDeploy initalized failed!")
RuntimeError: FastDeploy initalized failed!
```

```


import fastdeploy as fd
import numpy as np

model_url = "https://bj.bcebos.com/fastdeploy/models/mobilenetv2.tgz"
fd.download_and_decompress(model_url, path=".")


option = fd.RuntimeOption()

option.set_model_path("mobilenetv2/inference.pdmodel",
                      "mobilenetv2/inference.pdiparams")

# **** CPU 配置 ****
option.use_cpu()
option.use_ort_backend()
option.set_cpu_thread_num(12)

# 初始化构造runtime
runtime = fd.Runtime(option)

# 获取模型输入名
input_name = runtime.get_input_info(0).name

# 构造随机数据进行推理
results = runtime.infer({
    input_name: np.random.rand(1, 3, 224, 224).astype("float32")
})

print(results[0].shape)
```

**Comment by jiangjiajun** [comment]
鼠标右键选择`使用管理员权限`打开命令终端，再执行python程序

**Comment by monkeycc** [comment]
```
Traceback (most recent call last):
  File "C:\Users\User\.conda\envs\FastDeploy\lib\site-packages\fastdeploy\c_lib_wrap.py", line 164, in <module>
    from .libs.fastdeploy_main import *
ImportError: DLL load failed while importing fastdeploy_main: 动态链接库(DLL)初始化例程失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "DEMOcpu.py", line 1, in <module>
    import fastdeploy as fd
  File "C:\Users\User\.conda\envs\FastDeploy\lib\site-packages\fastdeploy\__init__.py", line 19, in <module>
    from .c_lib_wrap import (
  File "C:\Users\User\.conda\envs\FastDeploy\lib\site-packages\fastdeploy\c_lib_wrap.py", line 166, in <module>
    raise RuntimeError("FastDeploy initalized failed!")
RuntimeError: FastDeploy initalized failed!
```
换了conda环境
然后右键管理员打开Anaconda Powershell Prompt (anaconda3)
报错 动态链接库(DLL)初始化例程失败

百度了一下 
我的CPU不支持 avx
可能是这个问题导致
怎么办？

FastDeploy 应该还没有分版本吧
cpu、mkl 版本 noavx 
cpu、openblas 版本 noavx

@jiangjiajun

**Comment by jiangjiajun** [comment]
参考编译文档，编译时只打开ENABLE_ORT_BACKEND，不打开Paddle和OpenVINO后端试下

**Comment by monkeycc** [comment]
```
C:\1\FastDeploy\python>set ENABLE_ORT_BACKEND=ON

C:\1\FastDeploy\python>set ENABLE_PADDLE_BACKEND=OFF

C:\1\FastDeploy\python>set ENABLE_OPENVINO_BACKEND=OFF

C:\1\FastDeploy\python>set ENABLE_VISION=OFF

C:\1\FastDeploy\python>set ENABLE_TEXT=OFF

C:\1\FastDeploy\python>python setup.py build
running build
running build_py
running create_version
running cmake_build
Traceback (most recent call last):
  File "C:\1\FastDeploy\python\setup.py", line 418, in <module>
    setuptools.setup(
  File "C:\anaconda3\lib\site-packages\setuptools\__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "C:\anaconda3\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
    return run_commands(dist)
  File "C:\anaconda3\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
    dist.run_commands()
  File "C:\anaconda3\lib\site-packages\setuptools\_distutils\dist.py", line 973, in run_commands
    self.run_command(cmd)
  File "C:\anaconda3\lib\site-packages\setuptools\dist.py", line 1217, in run_command
    super().run_command(command)
  File "C:\anaconda3\lib\site-packages\setuptools\_distutils\dist.py", line 992, in run_command
    cmd_obj.run()
  File "C:\anaconda3\lib\site-packages\setuptools\command\build.py", line 24, in run
    super().run()
  File "C:\anaconda3\lib\site-packages\setuptools\_distutils\command\build.py", line 132, in run
    self.run_command(cmd_name)
  File "C:\anaconda3\lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "C:\anaconda3\lib\site-packages\setuptools\dist.py", line 1217, in run_command
    super().run_command(command)
  File "C:\anaconda3\lib\site-packages\setuptools\_distutils\dist.py", line 992, in run_command
    cmd_obj.run()
  File "C:\1\FastDeploy\python\setup.py", line 281, in run
    self.run_command('cmake_build')
  File "C:\anaconda3\lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "C:\anaconda3\lib\site-packages\setuptools\dist.py", line 1217, in run_command
    super().run_command(command)
  File "C:\anaconda3\lib\site-packages\setuptools\_distutils\dist.py", line 992, in run_command
    cmd_obj.run()
  File "C:\1\FastDeploy\python\setup.py", line 267, in run
    subprocess.check_call(cmake_args)
  File "C:\anaconda3\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\CMake\\bin\\cmake.exe', '-DPYTHON_INCLUDE_DIR=C:\\anaconda3\\include', '-DPYTHON_EXECUTABLE=C:\\anaconda3\\python.exe', '-DBUILD_FASTDEPLOY_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=paddle2onnx', '-DPY_EXT_SUFFIX=.cp39-win_amd64.pyd', '-DCMAKE_BUILD_TYPE=Release', '-DENABLE_RKNPU2_BACKEND=OFF', '-DENABLE_SOPHGO_BACKEND=OFF', '-DWITH_ASCEND=OFF', '-DENABLE_ORT_BACKEND=ON', '-DENABLE_OPENVINO_BACKEND=OFF', '-DENABLE_PADDLE_BACKEND=OFF', '-DENABLE_POROS_BACKEND=OFF', '-DENABLE_TRT_BACKEND=OFF', '-DENABLE_LITE_BACKEND=OFF', '-DPADDLELITE_URL=OFF', '-DENABLE_VISION=OFF', '-DENABLE_ENCRYPTION=OFF', '-DENABLE_FLYCV=OFF', '-DENABLE_TEXT=OFF', '-DWITH_GPU=OFF', '-DWITH_IPU=OFF', '-DWITH_KUNLUNXIN=OFF', '-DBUILD_ON_JETSON=OFF', '-DTRT_DIRECTORY=UNDEFINED', '-DCUDA_DIRECTORY=/usr/local/cuda', '-DLIBRARY_NAME=fastdeploy', '-DPY_LIBRARY_NAME=fastdeploy_main', '-DOPENCV_DIRECTORY=', '-DORT_DIRECTORY=', '-DPADDLEINFERENCE_DIRECTORY=', '-DRKNN2_TARGET_SOC=', '-DPY_VERSION=3.9', '-A', 'x64', '-T', 'host=x64', 'C:\\1\\FastDeploy']' returned non-zero exit status 3221225506.
```
<img width="443" alt="微信截图_20230203144102" src="https://user-images.githubusercontent.com/6490927/216530429-cd20672f-86c0-4ca3-a0c2-9a257b61719a.png">

```

python setup.py build
running build
running build_py
running create_version
running cmake_build
Traceback (most recent call last):
  File "setup.py", line 418, in <module>
    setuptools.setup(
  File "C:\Users\User\.conda\envs\FastDeploy\lib\site-packages\setuptools\__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\User\.conda\envs\FastDeploy\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
    return run_commands(dist)
  File "C:\Users\User\.conda\envs\FastDeploy\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
    dist.run_commands()
  File "C:\Users\User\.conda\envs\FastDeploy\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "C:\Users\User\.conda\envs\FastDeploy\lib\site-packages\setuptools\dist.py", line 1208, in run_command
    super().run_command(command)
  File "C:\Users\User\.conda\envs\FastDeploy\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\Users\User\.conda\envs\FastDeploy\lib\site-packages\setuptools\_distutils\command\build.py", line 132, in run
    self.run_command(cmd_name)
  File "C:\Users\User\.conda\envs\FastDeploy\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "C:\Users\User\.conda\envs\FastDeploy\lib\site-packages\setuptools\dist.py", line 1208, in run_command
    super().run_command(command)
  File "C:\Users\User\.conda\envs\FastDeploy\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "setup.py", line 281, in run
    self.run_command('cmake_build')
  File "C:\Users\User\.conda\envs\FastDeploy\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "C:\Users\User\.conda\envs\FastDeploy\lib\site-packages\setuptools\dist.py", line 1208, in run_command
    super().run_command(command)
  File "C:\Users\User\.conda\envs\FastDeploy\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "setup.py", line 267, in run
    subprocess.check_call(cmake_args)
  File "C:\Users\User\.conda\envs\FastDeploy\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\CMake\\bin\\cmake.exe', '-DPYTHON_INCLUDE_DIR=C:\\Users\\User\\.conda\\envs\\FastDeploy\\include', '-DPYTHON_EXECUTABLE=C:\\Users\\User\\.conda\\envs\\FastDeploy\\python.exe', '-DBUILD_FASTDEPLOY_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=paddle2onnx', '-DPY_EXT_SUFFIX=.cp38-win_amd64.pyd', '-DCMAKE_BUILD_TYPE=Release', '-DENABLE_RKNPU2_BACKEND=OFF', '-DENABLE_SOPHGO_BACKEND=OFF', '-DWITH_ASCEND=OFF', '-DENABLE_ORT_BACKEND=ON', '-DENABLE_OPENVINO_BACKEND=OFF', '-DENABLE_PADDLE_BACKEND=OFF', '-DENABLE_POROS_BACKEND=OFF', '-DENABLE_TRT_BACKEND=OFF', '-DENABLE_LITE_BACKEND=OFF', '-DPADDLELITE_URL=OFF', '-DENABLE_VISION=OFF', '-DENABLE_ENCRYPTION=OFF', '-DENABLE_FLYCV=OFF', '-DENABLE_TEXT=OFF', '-DWITH_GPU=OFF', '-DWITH_IPU=OFF', '-DWITH_KUNLUNXIN=OFF', '-DBUILD_ON_JETSON=OFF', '-DTRT_DIRECTORY=UNDEFINED', '-DCUDA_DIRECTORY=/usr/local/cuda', '-DLIBRARY_NAME=fastdeploy', '-DPY_LIBRARY_NAME=fastdeploy_main', '-DOPENCV_DIRECTORY=', '-DORT_DIRECTORY=', '-DPADDLEINFERENCE_DIRECTORY=', '-DRKNN2_TARGET_SOC=', '-DPY_VERSION=3.8', '-A', 'x64', '-T', 'host=x64', 'C:\\1\\FastDeploy']' returned non-zero exit status 3221225506
```

**Comment by jiangjiajun** [comment]
@monkeycc Hi， 我注意到你这上面编译出错了。 你能贴下你的系统版本和CPU版本信息吗？

另外如果Python无法编译，有尝试编译C++库吗，麻烦测下C++是否能编译成功（C++编译过程会有更详细的信息）

**Comment by monkeycc** [comment]
【系统平台】:Windows 10 专业版 64 位操作系统,  20H2  19042.985   基于 x64 的处理器
【硬件】： Intel(R) Atom(TM) x5-Z8300 CPU @ 1.44GHz 1.44 GHz


<img width="634" alt="微信截图_20230206142547" src="https://user-images.githubusercontent.com/6490927/216906292-3deda86c-962d-47f7-966c-b9e14507f9da.png">

CMakeGUI
```
Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
Use the default onnxruntime lib. The ONNXRuntime path: C:/1/FastDeploy/build/third_libs/install/onnxruntime
CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.25/Modules/ExternalProject.cmake:3075 (message):
  The DOWNLOAD_EXTRACT_TIMESTAMP option was not given and policy CMP0135 is
  not set.  The policy's OLD behavior will be used.  When using a URL
  download, the timestamps of extracted files should preferably be that of
  the time of extraction, otherwise code that depends on the extracted
  contents might not be rebuilt if the URL changes.  The OLD behavior
  preserves the timestamps from the archive instead, but this is usually not
  what you want.  Update your project to the NEW behavior or specify the
  DOWNLOAD_EXTRACT_TIMESTAMP option with a value of true to avoid this
  robustness issue.
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.25/Modules/ExternalProject.cmake:4185 (_ep_add_download_command)
  cmake/onnxruntime.cmake:98 (ExternalProject_Add)
  CMakeLists.txt:195 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.25/Modules/ExternalProject.cmake:3075 (message):
  The DOWNLOAD_EXTRACT_TIMESTAMP option was not given and policy CMP0135 is
  not set.  The policy's OLD behavior will be used.  When using a URL
  download, the timestamps of extracted files should preferably be that of
  the time of extraction, otherwise code that depends on the extracted
  contents might not be rebuilt if the URL changes.  The OLD behavior
  preserves the timestamps from the archive instead, but this is usually not
  what you want.  Update your project to the NEW behavior or specify the
  DOWNLOAD_EXTRACT_TIMESTAMP option with a value of true to avoid this
  robustness issue.
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.25/Modules/ExternalProject.cmake:4185 (_ep_add_download_command)
  cmake/paddle2onnx.cmake:67 (ExternalProject_Add)
  CMakeLists.txt:401 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.


*************FastDeploy Building Summary**********
  CMake version             : 3.25.2
  CMake command             : C:/Program Files/CMake/bin/cmake.exe
  System                    : Windows
  C++ compiler              : C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe
  C++ compiler version      : 19.29.30147.0
  CXX flags                 : /DWIN32 /D_WINDOWS /W3 /GR /EHsc
  Build type                : 
  Compile definitions       : FASTDEPLOY_LIB;EIGEN_STRONG_INLINE=inline;ENABLE_ORT_BACKEND;ENABLE_PADDLE2ONNX
  CMAKE_PREFIX_PATH         : 
  CMAKE_INSTALL_PREFIX      : C:/1/compiled_fastdeploy
  CMAKE_MODULE_PATH         : 

  FastDeploy version        : 0.0.0
  ENABLE_ORT_BACKEND        : ON
  ENABLE_RKNPU2_BACKEND     : OFF
  ENABLE_SOPHGO_BACKEND     : OFF
  ENABLE_PADDLE_BACKEND     : OFF
  ENABLE_LITE_BACKEND       : OFF
  ENABLE_POROS_BACKEND      : OFF
  ENABLE_TRT_BACKEND        : OFF
  ENABLE_OPENVINO_BACKEND   : OFF
  WITH_GPU                  : OFF
  WITH_ASCEND               : OFF
  WITH_TIMVX                : OFF
  WITH_KUNLUNXIN            : OFF
  ONNXRuntime version       : 1.12.0
  ENABLE_VISION             : OFF
  ENABLE_TEXT               : OFF
  ENABLE_ENCRYPTION         : OFF
Configuring done
Generating done
```

```

4>  正在创建库 C:/1/FastDeploy/build/Release/fastdeploy.lib 和对象 C:/1/FastDeploy/build/Release/fastdeploy.exp
4>fastdeploy.vcxproj -> C:\1\FastDeploy\build\Release\fastdeploy.dll
4>已完成生成项目“fastdeploy.vcxproj”的操作。
5>------ 已启动生成: 项目: ALL_BUILD, 配置: Release x64 ------
5>Building Custom Rule C:/1/FastDeploy/CMakeLists.txt
========== 生成: 成功 5 个，失败 0 个，最新 0 个，跳过 0 个 ==========
```

@jiangjiajun

**Comment by jiangjiajun** [comment]
@monkeycc 看起来是C++可以编译成功，但python失败是吗？

确认下在python编译时，是在命令行工具`x64 Native Tools Command Prompt for VS 2019`执行的`setup.py build`吗？

**Comment by monkeycc** [comment]
是的
在python编译时
x64 Native Tools Command Prompt for VS 2019
执行setup.py build

**Comment by monkeycc** [comment]
> py", line 1217, in run_command
>     super().run_command(command)
>   File "C:\anaconda3\lib\site-packages\setuptools\_distutils\dist.py", line 992, in run_command
>     cmd_obj.run()
>   File "C:\1\FastDeploy\python\setup.py", line 281, in run
>     self.run_command('cmake_build')
>   File "C:\anaconda3\lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
>     self.distribution.run_command(command)
>   File "C:\anaconda3\lib\site-packages\setuptools\dist.py", line 1217, in run_command
>     super().run_command(command)
>   File "C:\anaconda3\lib\site-packages\setuptools\_distutils\dist.py", line 992, in run_command
>     cmd_obj.run()
>   File "C:\1\FastDeploy\python\setup.py", line 267, in run
>     subprocess.check_call(cmake_args)
>   File "C:\anaconda3\lib\subprocess.py", line 373, in check_call
>     raise CalledProcessError(retcode, cmd)

是的
按照编译说明文档
x64 Native Tools Command Prompt for VS 2019
执行setup.py build

**Comment by jiangjiajun** [comment]
我再看了下上面的错误提示，是直接在cmake时就报错了（C++也报错）。 当前的cmake可以正常使用吗，试下执行 cmake --version 命令

**Comment by monkeycc** [comment]
重新安装了最新版的 cmake
cmake --version
cmake version 3.25.2
可以编译了

[python编译.txt](https://github.com/PaddlePaddle/FastDeploy/files/10663231/python.txt)
python的编译日志
看上去成功了

但是安装环境
```
 pip install fastdeploy_python-0.0.0-cp39-cp39-win_amd64.whl
Looking in indexes: https://mirrors.bfsu.edu.cn/pypi/web/simple
ERROR: fastdeploy_python-0.0.0-cp39-cp39-win_amd64.whl is not a supported wheel on this platform.
```

**Comment by jiangjiajun** [comment]
这个一般原因是由于wheel包与环境不同的原因导致，不同的地方可能在与以下两个地方
- 1. python版本，当使用的是pip命令，它不一定对应于你的Python39， 建议使用 `/Path/To/Python39.exe -m pip install fastdeploy_python-0.0.0-cp39-cp39-win_amd64.whl`
- 2. 系统版本，这里系统要求是Windows x64，如果你是x86的python.exe，也可能会出现上面的问题

**Comment by monkeycc** [comment]
感谢
全部问题解决
正常运行

因为是anaconda
编译的时候 默认在base环境
