### ISSUE TITLE
RuntimeError: FastDeploy initalized failed!

### ISSUE THREAD

**Issue by Firestick-Xia** [PaddlePaddle/FastDeploy#1298]
环境：ubuntu
cuda：11.4 cudnn：8.1
安装fastdeploy-gpu-python     1.0.3
报错信息：
`Traceback (most recent call last):
  File "test.py", line 2, in <module>
    import fastdeploy.vision as vision
  File "/home/xia.shuaipeng/ls/envs/test_api/lib/python3.8/site-packages/fastdeploy/__init__.py", line 19, in <module>
    from .c_lib_wrap import (
  File "/home/xia.shuaipeng/ls/envs/test_api/lib/python3.8/site-packages/fastdeploy/c_lib_wrap.py", line 166, in <module>
    raise RuntimeError("FastDeploy initalized failed!")
RuntimeError: FastDeploy initalized failed!`

**Comment by jiangjiajun** [comment]
试下使用docker 

nvidia-docker pull registry.baidubce.com/paddlepaddle/paddle:2.4.1-gpu-cuda11.7-cudnn8.4-trt8.4
