### ISSUE TITLE
RK3588 python  RuntimeError: FastDeploy initalized failed!

### ISSUE THREAD

**Issue by jiangq195** [PaddlePaddle/FastDeploy#1676]
cd FastDeploy/examples/vision/segmentation/paddleseg/semantic_segmentation/rockchip/rknpu2/python

python3 infer.py --model_file ./Portrait_PP_HumanSegV2_Lite_256x144_infer/Portrait_PP_HumanSegV2_Lite_256x144_infer_rk3588.rknn                 --config_file ./Portrait_PP_HumanSegV2_Lite_256x144_infer/deploy.yaml                 --image images/portrait_heng.jpg
Traceback (most recent call last):
  File "/home/firefly/.local/lib/python3.9/site-packages/fastdeploy/c_lib_wrap.py", line 164, in <module>
    from .libs.fastdeploy_main import *
ImportError: /home/firefly/.local/lib/python3.9/site-packages/fastdeploy/libs/fastdeploy_main.cpython-39-aarch64-linux-gnu.so: undefined symbol: _ZTIN10fastdeploy6vision14classification6ResNetE

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/firefly/projects/FastDeploy/examples/vision/segmentation/paddleseg/semantic_segmentation/rockchip/rknpu2/python/infer.py", line 14, in <module>
    import fastdeploy as fd
  File "/home/firefly/.local/lib/python3.9/site-packages/fastdeploy/__init__.py", line 53, in <module>
    from .c_lib_wrap import (
  File "/home/firefly/.local/lib/python3.9/site-packages/fastdeploy/c_lib_wrap.py", line 166, in <module>
    raise RuntimeError("FastDeploy initalized failed!")
RuntimeError: FastDeploy initalized failed!

**Comment by DefTruth** [comment]
请问你的编译命令是怎样的？

**Comment by Zheng-Bicheng** [comment]
你是在板端编译的嘛？看上去是你直接pip install fastdeploy了？
