### ISSUE TITLE
在AIStudio中报错undefined symbol: dnnl_layer_normalization_v2_forward_desc_init

### ISSUE THREAD

**Issue by magicly** [PaddlePaddle/FastDeploy#1706]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

AIStudio， 新建一个项目， paddle是2.4.1

## 问题日志及出现问题的操作流程
新建AiStudio， 安装FastDeploy， import fastdeploy就报错
```py
aistudio@jupyter-227854-5797577:~$ pip list | grep paddle
paddle-bfloat                  0.1.7
paddle2onnx                    1.0.0
paddlefsl                      1.1.0
paddlehub                      2.3.0
paddlenlp                      2.4.2
paddlepaddle-gpu               2.4.1.post112
tb-paddle                      0.3.6
x2paddle                       1.4.0
aistudio@jupyter-227854-5797577:~$ pip install numpy opencv-python fastdeploy-gpu-python -f https://www.paddlepaddle.org.cn/whl/fastdeploy.html
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Looking in links: https://www.paddlepaddle.org.cn/whl/fastdeploy.html
Requirement already satisfied: numpy in /opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages (1.23.5)
Requirement already satisfied: opencv-python in /opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages (4.6.0.66)
Collecting fastdeploy-gpu-python
  Downloading https://bj.bcebos.com/fastdeploy/release/wheels/fastdeploy_gpu_python-1.0.5-cp39-cp39-manylinux1_x86_64.whl (1353.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 GB 410.0 kB/s eta 0:00:00
Requirement already satisfied: pyyaml in /opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages (from fastdeploy-gpu-python) (5.1.2)
Requirement already satisfied: wheel in /opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages (from fastdeploy-gpu-python) (0.36.2)
Requirement already satisfied: tqdm in /opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages (from fastdeploy-gpu-python) (4.64.1)
Collecting fastdeploy-tools>=0.0.5
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/19/27/527bb120f18b72d79b280bc7a810e67a00e0a0a4a273d4543feede0e812f/fastdeploy_tools-0.0.5-py3-none-any.whl (10 kB)
Requirement already satisfied: fastapi in /opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages (from fastdeploy-gpu-python) (0.90.1)
Requirement already satisfied: requests in /opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages (from fastdeploy-gpu-python) (2.24.0)
Collecting uvicorn==0.16.0
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/a0/68/effcc7c39d79fbae86ad621ebcf28d63a3b9c111a885bc2b74c576ba8dc4/uvicorn-0.16.0-py3-none-any.whl (54 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.9/54.9 kB 1.0 MB/s eta 0:00:00
Requirement already satisfied: h11>=0.8 in /opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages (from uvicorn==0.16.0->fastdeploy-tools>=0.0.5->fastdeploy-gpu-python) (0.14.0)
Collecting asgiref>=3.4.0
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/8f/29/38d10a47b322a77b2d12c2b79c789f52956f733cb701d4d5157c76b5f238/asgiref-3.6.0-py3-none-any.whl (23 kB)
Requirement already satisfied: click>=7.0 in /opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages (from uvicorn==0.16.0->fastdeploy-tools>=0.0.5->fastdeploy-gpu-python) (8.0.4)
Requirement already satisfied: starlette<0.24.0,>=0.22.0 in /opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages (from fastapi->fastdeploy-gpu-python) (0.23.1)
Requirement already satisfied: pydantic!=1.7,!=1.7.1,!=1.7.2,!=1.7.3,!=1.8,!=1.8.1,<2.0.0,>=1.6.2 in /opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages (from fastapi->fastdeploy-gpu-python) (1.10.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages (from requests->fastdeploy-gpu-python) (1.25.11)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages (from requests->fastdeploy-gpu-python) (2019.9.11)
Requirement already satisfied: chardet<4,>=3.0.2 in /opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages (from requests->fastdeploy-gpu-python) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages (from requests->fastdeploy-gpu-python) (2.8)
Requirement already satisfied: typing-extensions>=4.2.0 in /opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages (from pydantic!=1.7,!=1.7.1,!=1.7.2,!=1.7.3,!=1.8,!=1.8.1,<2.0.0,>=1.6.2->fastapi->fastdeploy-gpu-python) (4.3.0)
Requirement already satisfied: anyio<5,>=3.4.0 in /opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages (from starlette<0.24.0,>=0.22.0->fastapi->fastdeploy-gpu-python) (3.6.1)
Requirement already satisfied: sniffio>=1.1 in /opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages (from anyio<5,>=3.4.0->starlette<0.24.0,>=0.22.0->fastapi->fastdeploy-gpu-python) (1.3.0)
Installing collected packages: asgiref, uvicorn, fastdeploy-tools, fastdeploy-gpu-python
  Attempting uninstall: uvicorn
    Found existing installation: uvicorn 0.20.0
    Uninstalling uvicorn-0.20.0:
      Successfully uninstalled uvicorn-0.20.0
Successfully installed asgiref-3.6.0 fastdeploy-gpu-python-1.0.5 fastdeploy-tools-0.0.5 uvicorn-0.16.0

[notice] A new release of pip available: 22.1.2 -> 23.0.1
[notice] To update, run: pip install --upgrade pip
aistudio@jupyter-227854-5797577:~$ python
Python 3.9.16 (main, Jan 11 2023, 16:05:54) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fastdeploy
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/fastdeploy/c_lib_wrap.py", line 164, in <module>
    from .libs.fastdeploy_main import *
ImportError: /opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/fastdeploy/libs/third_libs/paddle_inference/paddle/lib/libpaddle_inference.so: undefined symbol: dnnl_layer_normalization_v2_forward_desc_init

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/fastdeploy/__init__.py", line 53, in <module>
    from .c_lib_wrap import (
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/fastdeploy/c_lib_wrap.py", line 166, in <module>
    raise RuntimeError("FastDeploy initalized failed!")
RuntimeError: FastDeploy initalized failed!
>>> 
aistudio@jupyter-227854-5797577:~$ conda --version
conda 4.10.1
aistudio@jupyter-227854-5797577:~$ which python
/opt/conda/envs/python35-paddle120-env/bin/python
aistudio@jupyter-227854-5797577:~$ which pip
/opt/conda/envs/python35-paddle120-env/bin/pip
aistudio@jupyter-227854-5797577:~$ python --version
Python 3.9.16
```

**Comment by jiangjiajun** [comment]
将paddlepaddle升级到develop版最新

**Comment by clSpider** [comment]
将paddlepaddle升级到develop版最新 也报错 ImportError: /home/yscredit/anaconda3/envs/paddle/lib/python3.8/site-packages/fastdeploy/libs/third_libs/paddle_inference/paddle/lib/libpaddle_inference.so: undefined symbol: dnnl_layer_normalization_v2_forward_desc_init

**Comment by jiangjiajun** [comment]
@magicly @clSpider 
请直接修改下这个代码文件
```
/home/yscredit/anaconda3/envs/paddle/lib/python3.8/site-packages/fastdeploy/__init__.py
```
将里面的`try: import paddle`代码逻辑注释掉，即可使用

**Comment by clSpider** [comment]
@jiangjiajun  注释之后 还是报错：
我的环境是linux  centos  conda + paddlepaddle=2.4.2 + paddlenlp=2.4.0 + fastdeploy-python=1.0.5 + fastdeploy-tools + 0.0.5
安装方式： pip install numpy opencv-python fastdeploy-python -f https://www.paddlepaddle.org.cn/whl/fastdeploy.html


WARNING:root:Failed to create a symbolic link pointing to /home/yscredit/anaconda3/envs/paddle/lib/python3.8/site-packages/fastdeploy/libs/third_libs/tensorrt/lib/libnvcaffe_parser.so.8 by an unprivileged user. It may failed when you use Paddle TensorRT backend. Please use administator privilege to import fastdeploy at first time.
Traceback (most recent call last):
  File "/home/yscredit/anaconda3/envs/paddle/lib/python3.8/site-packages/fastdeploy/c_lib_wrap.py", line 164, in <module>
    from .libs.fastdeploy_main import *
ImportError: /home/yscredit/anaconda3/envs/paddle/lib/python3.8/site-packages/fastdeploy/libs/third_libs/paddle_inference/paddle/lib/libpaddle_inference.so: undefined symbol: dnnl_layer_normalization_v2_forward_desc_init

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fastpipeline.py", line 7, in <module>
    import fastdeploy as fd
  File "/home/yscredit/anaconda3/envs/paddle/lib/python3.8/site-packages/fastdeploy/__init__.py", line 53, in <module>
    from .c_lib_wrap import (
  File "/home/yscredit/anaconda3/envs/paddle/lib/python3.8/site-packages/fastdeploy/c_lib_wrap.py", line 166, in <module>
    raise RuntimeError("FastDeploy initalized failed!")
RuntimeError: FastDeploy initalized failed!

**Comment by ncoll** [comment]
遇到同样的报错，把同一个环境下的paddlepaddle-gpu卸载了，我这就能执行了，不知道是不是这两个会冲突？

**Comment by clSpider** [comment]
@ncoll 我都没装paddlepaddle-gpu

**Comment by Toefinder** [comment]
I had the same issue with `fastdeploy-python==1.0.5` and running a simple `import fastdeploy`.
Downgrading to `fastdeploy-python==1.0.4` solves the issue. Not sure if it helps you.

**Comment by CrazyStone6** [comment]
> 

我也是卸载了就成功了
