### ISSUE TITLE
[BUG] fastdeploy部署stable diffusion - tensorrt 出现内存溢出的现象

### ISSUE THREAD

**Issue by sanbuphy** [PaddlePaddle/FastDeploy#1805]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： dev最新
- 【系统平台】: ubuntu 20.04
- 【硬件】： 3060
- 【编译语言】： Python 3.8 

## 问题日志及出现问题的操作流程
关联issue：https://github.com/PaddlePaddle/PaddleNLP/issues/5617

参考：https://github.com/PaddlePaddle/PaddleNLP/tree/develop/ppdiffusers/deploy
运行命令：
```bash
python text_to_img_infer.py --model_dir stable-diffusion-v1-5/ --scheduler "euler_ancestral" --backend paddle_tensorrt --use_fp16 True --device gpu
```

现象：
![aa9caa5b0caa4493eddc1c15bccdb38](https://user-images.githubusercontent.com/96160062/231381225-ba56171c-93ae-48d0-9325-9dc450163a73.png)

**Comment by sanbuphy** [comment]
@DefTruth  麻烦大佬有空的时候看一眼~  感谢

**Comment by sanbuphy** [comment]
新的问题现象，如果使用aistudio A100会出现：
![image](https://user-images.githubusercontent.com/96160062/231424016-550ddffe-46bc-4eca-9d4c-1c19960e85f4.png)

**Comment by DefTruth** [comment]
你用的fd版本和paddle版本分别是什么？

**Comment by sanbuphy** [comment]
> 你用的fd版本和paddle版本分别是什么？

都是最新版安装的 dev，根据：https://github.com/PaddlePaddle/FastDeploy/issues/1798#issuecomment-1503109477

**Comment by lxp521125** [comment]
使用版本：fastdeploy-gpu-python==1.0.7
在飞桨应用下部署，报错。
可以给个推荐版本不？

2023-07-18T09:44:43.245964607Z Traceback (most recent call last):
2023-07-18T09:44:43.245967581Z   File "/home/serving/飞桨画图1689670204773/app.gradio.py", line 3, in <module>
2023-07-18T09:44:43.246005154Z     from ppdiffusers import StableDiffusionPipeline
2023-07-18T09:44:43.246014525Z   File "/opt/conda/envs/py310/lib/python3.10/site-packages/ppdiffusers/__init__.py", line 18, in <module>
2023-07-18T09:44:43.246017921Z     from . import patches
2023-07-18T09:44:43.246021391Z   File "/opt/conda/envs/py310/lib/python3.10/site-packages/ppdiffusers/patches/__init__.py", line 15, in <module>
2023-07-18T09:44:43.246089734Z     from . import ppnlp_patch_utils, tomesd_patch_utils, webui_lora_patch_utils
2023-07-18T09:44:43.246131283Z   File "/opt/conda/envs/py310/lib/python3.10/site-packages/ppdiffusers/patches/ppnlp_patch_utils.py", line 1085, in <module>
2023-07-18T09:44:43.246294614Z     from ..pipelines.alt_diffusion.modeling_roberta_series import (
2023-07-18T09:44:43.246300621Z   File "/opt/conda/envs/py310/lib/python3.10/site-packages/ppdiffusers/pipelines/__init__.py", line 33, in <module>
2023-07-18T09:44:43.246329497Z     from .dance_diffusion import DanceDiffusionPipeline
2023-07-18T09:44:43.246334048Z   File "/opt/conda/envs/py310/lib/python3.10/site-packages/ppdiffusers/pipelines/dance_diffusion/__init__.py", line 17, in <module>
2023-07-18T09:44:43.246391909Z     from .pipeline_dance_diffusion import DanceDiffusionPipeline
2023-07-18T09:44:43.246398494Z   File "/opt/conda/envs/py310/lib/python3.10/site-packages/ppdiffusers/pipelines/dance_diffusion/pipeline_dance_diffusion.py", line 20, in <module>
2023-07-18T09:44:43.246416850Z     from ..pipeline_utils import AudioPipelineOutput, DiffusionPipeline
2023-07-18T09:44:43.246420838Z   File "/opt/conda/envs/py310/lib/python3.10/site-packages/ppdiffusers/pipelines/pipeline_utils.py", line 83, in <module>
2023-07-18T09:44:43.246510581Z     from .fastdeploy_utils import FastDeployRuntimeModel
2023-07-18T09:44:43.246513615Z   File "/opt/conda/envs/py310/lib/python3.10/site-packages/ppdiffusers/pipelines/fastdeploy_utils.py", line 69, in <module>
2023-07-18T09:44:43.246516109Z     import fastdeploy as fd
2023-07-18T09:44:43.246518502Z   File "/opt/conda/envs/py310/lib/python3.10/site-packages/fastdeploy/__init__.py", line 122, in <module>
2023-07-18T09:44:43.246588984Z     from .c_lib_wrap import (
2023-07-18T09:44:43.246594848Z   File "/opt/conda/envs/py310/lib/python3.10/site-packages/fastdeploy/c_lib_wrap.py", line 166, in <module>
2023-07-18T09:44:43.246616657Z     raise RuntimeError(f"FastDeploy initalized failed! Error: {e}")
2023-07-18T09:44:43.246620508Z RuntimeError: FastDeploy initalized failed! Error: /opt/conda/envs/py310/lib/python3.10/site-packages/fastdeploy/libs/third_libs/paddle_inference/paddle/lib/libpaddle_inference.so: undefined symbol: dnnl_layer_normalization_v2_forward_desc_init
