### ISSUE TITLE
onnx转rknn模型出错

### ISSUE THREAD

**Issue by itouchsky** [PaddlePaddle/FastDeploy#1905]
测试Paddle/FastDeploy/examples/vision/keypointdetection/tiny_pose/rknpu2/cpp/这个例子转换模型时出错，信息如下：

python tools/rknpu2/export.py --config_path tools/rknpu2/config/PP_TinyPose_256x192_unquantized.yaml --target_platform rk3588
{'mean': [[123.675, 116.28, 103.53]], 'std': [[58.395, 57.12, 57.375]], 'model_path': './PP_TinyPose_256x192_infer/PP_TinyPose_256x192_infer.onnx', 'outputs_nodes': ['conv2d_441.tmp_1'], 'do_quantization': False, 'dataset': None, 'output_folder': './PP_TinyPose_256x192_infer'}
W __init__: rknn-toolkit2 version: 1.4.0-22dcfef4
W load_onnx: If you don't need to crop the model, don't set 'inputs'/'input_size_list'/'outputs'!
W load_onnx: It is recommended onnx opset 12, but your onnx model opset is 11!
E load_onnx: Catch exception when loading onnx model: /home/gaylord/Paddle/FastDeploy/PP_TinyPose_256x192_infer/PP_TinyPose_256x192_infer.onnx!
E load_onnx: Traceback (most recent call last):
E load_onnx:   File "rknn/api/rknn_base.py", line 1152, in rknn.api.rknn_base.RKNNBase.load_onnx
E load_onnx:   File "rknn/api/rknn_base.py", line 617, in rknn.api.rknn_base.RKNNBase._create_ir_and_inputs_meta
E load_onnx: TypeError: '<=' not supported between instances of 'NoneType' and 'int'
Traceback (most recent call last):
  File "tools/rknpu2/export.py", line 52, in <module>
    assert ret == 0, "Load model failed!"
AssertionError: Load model failed!

**Comment by itouchsky** [comment]
重新安装一些依赖包后，就可以转换了，先关闭
