### ISSUE TITLE
PaddleOCR服务化部署仅能识别样例图片，其他任何图片都报错无法正常识别

### ISSUE THREAD

**Issue by 0Lisixian0** [PaddlePaddle/FastDeploy#1931]
- 【FastDeploy版本】fastdeploy:1.0.4-gpu-cuda11.4-trt8.5-21.10
- 【编译命令】参考(https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/vision/ocr/PP-OCR/serving/fastdeploy_serving)
- 【系统平台】: Linux x64
- 【硬件】：  Nvidia GPU Tesla P4， CUDA 11.6 CUDNN 8.5
- 【编译语言】：Python(3.9）

## 问题日志及出现问题的操作流程
- 【无法正常识别样例以外的图片】
- - 先执行`examples`下的部署示例，包括使用examples提供的模型，确认可以正确执行
- - 按照教程，服务端运行后，在客户端运行python3 client.py，对于样例图片12.jpg可以正常识别，识别结果：
-(ocr) [topsci@localhost fastdeploy_serving]$ python3 client.py
text= 上海斯格威铂尔大酒店   score= 0.9804123044013977   bbox= [ 42 413 483 391 484 428  43 450]
text= 打浦路15号   score= 0.9606184363365173   bbox= [187 456 399 448 400 480 188 488]
text= 绿洲仕格维花园公寓   score= 0.9806857705116272   bbox= [ 23 507 513 488 515 529  24 548]
text= 打浦路252935号   score= 0.9498506784439087   bbox= [ 74 553 427 542 428 571  75 582]

-- 如果更改client.py文件中的图片，例如将im = cv2.imread("12.jpg")改为im = cv2.imread("002.jpg")，“002.jpg”为另一张图片，则会报错，报错内容：
-(ocr) [topsci@localhost fastdeploy_serving]$ python3 client.py
Traceback (most recent call last):
  File "/home/topsci/code/OCR/fastdeploy_serving/client.py", line 100, in <module>
    result = runner.Run([im, ])
  File "/home/topsci/code/OCR/fastdeploy_serving/client.py", line 71, in Run
    results = self._client.infer(
  File "/home/topsci/anaconda3/envs/ocr/lib/python3.9/site-packages/tritonclient/grpc/__init__.py", line 1446, in infer
    raise_error_grpc(rpc_error)
  File "/home/topsci/anaconda3/envs/ocr/lib/python3.9/site-packages/tritonclient/grpc/__init__.py", line 76, in raise_error_grpc
    raise get_error_grpc(rpc_error) from None
tritonclient.utils.InferenceServerException: [StatusCode.INTERNAL] in ensemble 'pp_ocr', Failed to process the request(s) for model instance 'det_postprocess_0', message: TritonModelException: in ensemble 'cls_pp', softmax_0.tmp_0: failed to perform CUDA copy: invalid argument

At:
  /ocr_serving/code/OCR/fastdeploy_serving/models/det_postprocess/1/model.py(176): execute

想问一下这是怎么回事。

**Comment by 0Lisixian0** [comment]
更正：是每次重启服务端后第一张图片可以正常识别，更改图片再次识别后会出现乱码或者报错。
乱码：
![842e968060766cd4ec110545c650c68](https://github.com/PaddlePaddle/FastDeploy/assets/87418560/27c19b37-8176-4a6e-ac27-7a21fe74d56b)
报错内容：
Traceback (most recent call last):
File "/home/topsci/code/OCR/fastdeploy_serving/client.py", line 100, in
result = runner.Run([im, ])
File "/home/topsci/code/OCR/fastdeploy_serving/client.py", line 71, in Run
results = self._client.infer(
File "/home/topsci/anaconda3/envs/ocr/lib/python3.9/site-packages/tritonclient/grpc/init.py", line 1446, in infer
raise_error_grpc(rpc_error)
File "/home/topsci/anaconda3/envs/ocr/lib/python3.9/site-packages/tritonclient/grpc/init.py", line 76, in raise_error_grpc
raise get_error_grpc(rpc_error) from None
tritonclient.utils.InferenceServerException: [StatusCode.INTERNAL] in ensemble 'pp_ocr', Failed to process the request(s) for model instance 'det_postprocess_0', message: TritonModelException: in ensemble 'cls_pp', softmax_0.tmp_0: failed to perform CUDA copy: invalid argument

At:
/ocr_serving/code/OCR/fastdeploy_serving/models/det_postprocess/1/model.py(176): execute

情况和https://github.com/PaddlePaddle/FastDeploy/issues/1672 类似，需要通过不断地重启服务端才能正常识别图片。想问一下这种情况怎么办，有什么办法能启动服务后识别多张图片呢？
