### ISSUE TITLE
【提供的ONNX转换RKNN例子无法执行】ONNX转换RKNN错误

### ISSUE THREAD

**Issue by qiulongquan** [PaddlePaddle/FastDeploy#1945]
## 环境

- 【FastDeploy版本】： 使用官网提供的C++在rk3588上面编译 fastdeploy 测试没有问题
- 【编译命令】 使用官网提供的C++在rk3588上面编译 fastdeploy 测试没有问题
- 【系统平台】: Linux x64(Ubuntu 20.04)
- 【硬件】： RK3588
- 【编译语言】： Python3.8

## 问题日志及出现问题的操作流程
参照下面的例子尝试ONNX模型转换RKNN模型（模型对象 picodet_s_416_coco_lcnet_unquantized），但是出现错误
https://github.com/PaddlePaddle/FastDeploy/blob/develop/examples/vision/detection/paddledetection/rknpu2/README_CN.md
已经确认  固定shape到 [1,3,416,416] 成功
paddle2onnx命令
paddle2onnx --model_dir /home/seikoist-qiu/total_test_for_emotion/PPHGNet_small_v6_infer/picodet_s_416_coco_lcnet \
--model_filename model.pdmodel \
--params_filename model.pdiparams \
--opset_version 12 \
--save_file model.onnx --enable_dev_version True \
--enable_onnx_checker True

## 错误日志
···
(rk3588) topeet@ubuntu-vmware16:~/ml/rknn-toolkit2/examples/onnx/yolov5$ python onnx_rknn.py 
W __init__: rknn-toolkit2 version: 1.4.0-22dcfef4
--> Config model
W config: 'target_platform' is None, use rk3566 as default, Please set according to the actual platform!
done
--> Loading model
W load_onnx: The config.mean_values is None, zeros will be set for input 1!
W load_onnx: The config.std_values is None, ones will be set for input 1!
done
--> Building model
I base_optimize ...
I base_optimize done.
I 
I fold_constant ...
E build: Catch exception when building RKNN model!
E build: Traceback (most recent call last):
E build:   File "rknn/api/rknn_base.py", line 1541, in rknn.api.rknn_base.RKNNBase.build
E build:   File "rknn/api/graph_optimizer.py", line 627, in rknn.api.graph_optimizer.GraphOptimizer.fold_constant
E build:   File "rknn/api/session.py", line 28, in rknn.api.session.Session.__init__
E build:   File "rknn/api/session.py", line 71, in rknn.api.session.Session.sess_build
E build:   File "/home/topeet/anaconda3/envs/rk3588/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 335, in __init__
E build:     self._create_inference_session(providers, provider_options, disabled_optimizers)
E build:   File "/home/topeet/anaconda3/envs/rk3588/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 370, in _create_inference_session
E build:     sess = C.InferenceSession(session_options, self._model_bytes, False, self._read_config_from_model)
E build: onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Failed to load model with error: /onnxruntime_src/onnxruntime/core/graph/model.cc:129 onnxruntime::Model::Model(onnx::ModelProto&&, const PathString&, const IOnnxRuntimeOpSchemaRegistryList*, const onnxruntime::logging::Logger&, bool) Unsupported model IR version: 9, max supported IR version: 8
Build model failed!
···

**Comment by qiulongquan** [comment]
有哪位大神 可以解决这个问题吗 在线等

**Comment by qiulongquan** [comment]
问题已经解决 暂时先关闭 这个问题主要是自己对于问题理解导致 不是共同问题
