### ISSUE TITLE
【ppocrv3_cls.yaml】转换rknn模型报错【Field 'shape' of 'type' is required but missing.】

### ISSUE THREAD

**Issue by neotty** [PaddlePaddle/FastDeploy#2038]
## 环境

- 【FastDeploy版本】： rknn-toolkit2==1.5.0+1fa95b5c  paddle2onnx==1.0.6
- 【编译命令】python FastDeploy/tools/rknpu2/export.py --config_path FastDeploy/tools/rknpu2/config/ppocrv3_cls.yaml --target_platform rk3588
- 【系统平台】: Linux x64(Ubuntu 22.04)
- 【硬件】： Nvidia GPU 3090， CUDA 11.7
- 【编译语言】： Python 3.10

## 问题日志及出现问题的操作流程
- 【模型转换出错】
```bash
(rknn) ➜  paddle git:(master) python FastDeploy/tools/rknpu2/export.py --config_path FastDeploy/tools/rknpu2/config/ppocrv3_cls.yaml --target_platform rk3588
{'mean': [[127.5, 127.5, 127.5]], 'std': [[127.5, 127.5, 127.5]], 'model_path': './ch_ppocr_mobile_v2.0_cls_infer/ch_ppocr_mobile_v2.0_cls_infer.onnx', 'outputs_nodes': None, 'do_quantization': False, 'dataset': None, 'output_folder': './ch_ppocr_mobile_v2.0_cls_infer'}
W __init__: rknn-toolkit2 version: 1.5.0+1fa95b5c
W load_onnx: It is recommended onnx opset 12, but your onnx model opset is 9!
E load_onnx: Catch exception when loading onnx model: /srv/ssd/github/rockchip/rknn_model_foo/paddle/ch_ppocr_mobile_v2.0_cls_infer/ch_ppocr_mobile_v2.0_cls_infer.onnx!
E load_onnx: Traceback (most recent call last):
E load_onnx:   File "rknn/api/rknn_base.py", line 1382, in rknn.api.rknn_base.RKNNBase.load_onnx
E load_onnx:   File "rknn/api/rknn_base.py", line 658, in rknn.api.rknn_base.RKNNBase._create_ir_and_inputs_meta
E load_onnx:   File "rknn/api/ir_graph.py", line 58, in rknn.api.ir_graph.IRGraph.__init__
E load_onnx:   File "rknn/api/ir_graph.py", line 503, in rknn.api.ir_graph.IRGraph.rebuild
E load_onnx:   File "/srv/ssd/anaconda3/envs/rknn/lib/python3.10/site-packages/onnx/checker.py", line 119, in check_model
E load_onnx:     C.check_model(protobuf_string, full_check)
E load_onnx: onnx.onnx_cpp2py_export.checker.ValidationError: Field 'shape' of 'type' is required but missing.
W If you can't handle this error, please try updating to the latest version of the toolkit2 and runtime from:
  https://eyun.baidu.com/s/3eTDMk6Y (Pwd: rknn)  Path: RK_NPU_SDK / RK_NPU_SDK_1.X.0 / develop /
  If the error still exists in the latest version, please collect the corresponding error logs and the model,
  convert script, and input data that can reproduce the problem, and then submit an issue on:
  https://redmine.rock-chips.com (Please consult our sales or FAE for the redmine account)
Traceback (most recent call last):
  File "/srv/ssd/github/rockchip/rknn_model_foo/paddle/FastDeploy/tools/rknpu2/export.py", line 52, in <module>
    assert ret == 0, "Load model failed!"
AssertionError: Load model failed!
```

**Comment by liuzong616** [comment]
你好，请问你的问题解决了吗？我也遇到了相同的问题
