### ISSUE TITLE
运行demo或者编译时，会有libcudart.so.11.0 找不到的报错

### ISSUE THREAD

**Issue by Sooguo** [PaddlePaddle/FastDeploy#2124]
错误log如下，我的cuda环境时10.2.89，这个cuda版本不能更换，请问下作者，怎么适配10.2.89的cuda？谢谢

root@e49e02585200:/home/FastDeploy/python_demo# python3 paddledetection.py 
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/fastdeploy/c_lib_wrap.py", line 164, in <module>
    from .libs.fastdeploy_main import *
ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "paddledetection.py", line 3, in <module>
    import fastdeploy.vision as vision
  File "/usr/local/lib/python3.7/site-packages/fastdeploy/__init__.py", line 122, in <module>
    from .c_lib_wrap import (
  File "/usr/local/lib/python3.7/site-packages/fastdeploy/c_lib_wrap.py", line 166, in <module>
    raise RuntimeError(f"FastDeploy initalized failed! Error: {e}")
RuntimeError: FastDeploy initalized failed! Error: libcudart.so.11.0: cannot open shared object file: No such file or directory

**Comment by tingaicompass** [comment]
这个问题我遇到过：记录下来你试试能不能解决你的问题

简约版（省流）
在激活后执行export LD_LIBRARY_PATH="$CONDA_PREFIX/lib"将包括libcudart.so.11.0如果你想让它自动化，将此内容添加到env-prefix/etc/conda/activate.d/env_vars.sh，这将在conda activate上运行脚本并设置LD_LIBRARY_PATH


[Linux和Windows系统下:安装Anaconda、Paddle、tensorflow、pytorch，GPU[cuda、cudnn]、CPU安装教学,以及查看CPU、GPU内存使用情况](https://blog.csdn.net/sinat_39620217/article/details/131675175)
