### ISSUE TITLE
Rust win  编译错误

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/FastDeploy#2138]
https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/application/rust/yolov8

系统
win11

llvm
MSYS2
已安装

建议弄win版教程
或者win msvc教程

https://crates.io/
建议crates也弄一个

fastdeploy-win-x64-gpu-0.0.0
fastdeploy_capi
放根目录了

build.rs
```
fn main() {
    println!("cargo:rustc-link-search=./fastdeploy-win-x64-gpu-0.0.0/lib");
    println!("cargo:rustc-link-lib=fastdeploy");
    println!("cargo:rerun-if-changed=wrapper.h");

    let headers_dir = PathBuf::from("./fastdeploy-win-x64-gpu-0.0.0/include");

```

wrapper.h
```
#include <fastdeploy_capi/vision.h>
```

```
[ERROR rust_analyzer::main_loop] FetchBuildDataError:
error: failed to run custom build command for `infer v0.1.0 (E:\2023_Code_Paddle\FastDeploy\examples\application\rust\yolov8)`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `E:\2023_Code_Paddle\FastDeploy\examples\application\rust\yolov8\target\debug\build\infer-4d99eefc0e05ce0c\build-script-build` (exit code: 101)
  --- stdout
  cargo:rustc-link-search=./fastdeploy-win-x64-gpu-0.0.0/lib
  cargo:rustc-link-lib=fastdeploy
  cargo:rerun-if-changed=wrapper.h

  --- stderr
  wrapper.h:1:10: error: 'fastdeploy_capi/vision.h' file not found with <angled> include; use "quotes" instead
  ./fastdeploy_capi/vision.h:16:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/core/config.h [-Wmicrosoft-include]
  ./fastdeploy_capi/vision.h:19:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/vision/classification/ppcls/model.h [-Wmicrosoft-include]
  ./fastdeploy_capi/vision/classification/ppcls/model.h:17:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/core/fd_common.h [-Wmicrosoft-include]
  ./fastdeploy_capi/vision/classification/ppcls/model.h:18:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/core/fd_type.h [-Wmicrosoft-include]
  ./fastdeploy_capi/core/fd_type.h:20:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/runtime/enum_variables.h [-Wmicrosoft-include]
  ./fastdeploy_capi/core/fd_type.h:21:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/core/fd_common.h [-Wmicrosoft-include]
  ./fastdeploy_capi/vision/classification/ppcls/model.h:19:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/runtime/runtime_option.h [-Wmicrosoft-include]
  ./fastdeploy_capi/runtime/runtime_option.h:17:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/core/fd_type.h [-Wmicrosoft-include]
  ./fastdeploy_capi/vision/classification/ppcls/model.h:20:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/vision/result.h [-Wmicrosoft-include]
  ./fastdeploy_capi/vision/result.h:17:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/core/fd_common.h [-Wmicrosoft-include]
  ./fastdeploy_capi/vision/result.h:18:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/core/fd_type.h [-Wmicrosoft-include]
  ./fastdeploy_capi/vision.h:20:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/vision/detection/ppdet/model.h [-Wmicrosoft-include]
  ./fastdeploy_capi/vision/detection/ppdet/model.h:17:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/core/fd_common.h [-Wmicrosoft-include]
  ./fastdeploy_capi/vision/detection/ppdet/model.h:18:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/core/fd_type.h [-Wmicrosoft-include]
  ./fastdeploy_capi/vision/detection/ppdet/model.h:19:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/runtime/runtime_option.h [-Wmicrosoft-include]
  ./fastdeploy_capi/vision/detection/ppdet/model.h:20:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/vision/result.h [-Wmicrosoft-include]
  ./fastdeploy_capi/vision/detection/ppdet/model.h:21:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/vision/detection/ppdet/base_define.h [-Wmicrosoft-include]
  ./fastdeploy_capi/vision.h:21:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/vision/detection/contrib/yolo/model.h [-Wmicrosoft-include]
  ./fastdeploy_capi/vision/detection/contrib/yolo/model.h:17:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/core/fd_common.h [-Wmicrosoft-include]
  ./fastdeploy_capi/vision/detection/contrib/yolo/model.h:18:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/core/fd_type.h [-Wmicrosoft-include]
  ./fastdeploy_capi/vision/detection/contrib/yolo/model.h:19:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/runtime/runtime_option.h [-Wmicrosoft-include]
  ./fastdeploy_capi/vision/detection/contrib/yolo/model.h:20:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/vision/result.h [-Wmicrosoft-include]
  ./fastdeploy_capi/vision/detection/contrib/yolo/model.h:21:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/vision/detection/contrib/yolo/base_define.h [-Wmicrosoft-include]
  ./fastdeploy_capi/vision.h:22:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/vision/ocr/ppocr/model.h [-Wmicrosoft-include]
  ./fastdeploy_capi/vision/ocr/ppocr/model.h:17:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/core/fd_common.h [-Wmicrosoft-include]
  ./fastdeploy_capi/vision/ocr/ppocr/model.h:18:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/core/fd_type.h [-Wmicrosoft-include]
  ./fastdeploy_capi/vision/ocr/ppocr/model.h:19:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/runtime/runtime_option.h [-Wmicrosoft-include]
  ./fastdeploy_capi/vision/ocr/ppocr/model.h:20:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/vision/result.h [-Wmicrosoft-include]
  ./fastdeploy_capi/vision/ocr/ppocr/model.h:21:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/vision/ocr/ppocr/base_define.h [-Wmicrosoft-include]
  ./fastdeploy_capi/vision.h:23:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/vision/segmentation/ppseg/model.h [-Wmicrosoft-include]
  ./fastdeploy_capi/vision/segmentation/ppseg/model.h:17:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/core/fd_common.h [-Wmicrosoft-include]
  ./fastdeploy_capi/vision/segmentation/ppseg/model.h:18:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/core/fd_type.h [-Wmicrosoft-include]
  ./fastdeploy_capi/vision/segmentation/ppseg/model.h:19:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/runtime/runtime_option.h [-Wmicrosoft-include]
  ./fastdeploy_capi/vision/segmentation/ppseg/model.h:20:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/vision/result.h [-Wmicrosoft-include]
  ./fastdeploy_capi/vision.h:24:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/vision/result.h [-Wmicrosoft-include]
  ./fastdeploy_capi/vision.h:25:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/vision/visualize.h [-Wmicrosoft-include]
  ./fastdeploy_capi/vision/visualize.h:17:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/core/fd_common.h [-Wmicrosoft-include]
  ./fastdeploy_capi/vision/visualize.h:18:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/core/fd_type.h [-Wmicrosoft-include]
  ./fastdeploy_capi/vision/visualize.h:19:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/vision/result.h [-Wmicrosoft-include]
  ./fastdeploy_capi/vision.h:28:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/core/fd_type.h [-Wmicrosoft-include]
  ./fastdeploy_capi/vision.h:29:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/runtime/runtime_option.h [-Wmicrosoft-include]
  wrapper.h:1:10: error: 'fastdeploy_capi/vision.h' file not found with <angled> include; use "quotes" instead, err: true
  ./fastdeploy_capi/vision.h:16:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/core/config.h [-Wmicrosoft-include], err: false
  ./fastdeploy_capi/vision.h:19:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/vision/classification/ppcls/model.h [-Wmicrosoft-include], err: false
  ./fastdeploy_capi/vision/classification/ppcls/model.h:17:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/core/fd_common.h [-Wmicrosoft-include], err: false
  ./fastdeploy_capi/vision/classification/ppcls/model.h:18:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/core/fd_type.h [-Wmicrosoft-include], err: false
  ./fastdeploy_capi/core/fd_type.h:20:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/runtime/enum_variables.h [-Wmicrosoft-include], err: false
  ./fastdeploy_capi/core/fd_type.h:21:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/core/fd_common.h [-Wmicrosoft-include], err: false
  ./fastdeploy_capi/vision/classification/ppcls/model.h:19:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/runtime/runtime_option.h [-Wmicrosoft-include], err: false
  ./fastdeploy_capi/runtime/runtime_option.h:17:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/core/fd_type.h [-Wmicrosoft-include], err: false
  ./fastdeploy_capi/vision/classification/ppcls/model.h:20:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/vision/result.h [-Wmicrosoft-include], err: false
  ./fastdeploy_capi/vision/result.h:17:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/core/fd_common.h [-Wmicrosoft-include], err: false
  ./fastdeploy_capi/vision/result.h:18:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/core/fd_type.h [-Wmicrosoft-include], err: false
  ./fastdeploy_capi/vision.h:20:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/vision/detection/ppdet/model.h [-Wmicrosoft-include], err: false
  ./fastdeploy_capi/vision/detection/ppdet/model.h:17:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/core/fd_common.h [-Wmicrosoft-include], err: false
  ./fastdeploy_capi/vision/detection/ppdet/model.h:18:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/core/fd_type.h [-Wmicrosoft-include], err: false
  ./fastdeploy_capi/vision/detection/ppdet/model.h:19:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/runtime/runtime_option.h [-Wmicrosoft-include], err: false
  ./fastdeploy_capi/vision/detection/ppdet/model.h:20:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/vision/result.h [-Wmicrosoft-include], err: false
  ./fastdeploy_capi/vision/detection/ppdet/model.h:21:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/vision/detection/ppdet/base_define.h [-Wmicrosoft-include], err: false
  ./fastdeploy_capi/vision.h:21:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/vision/detection/contrib/yolo/model.h [-Wmicrosoft-include], err: false
  ./fastdeploy_capi/vision/detection/contrib/yolo/model.h:17:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/core/fd_common.h [-Wmicrosoft-include], err: false
  ./fastdeploy_capi/vision/detection/contrib/yolo/model.h:18:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/core/fd_type.h [-Wmicrosoft-include], err: false
  ./fastdeploy_capi/vision/detection/contrib/yolo/model.h:19:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/runtime/runtime_option.h [-Wmicrosoft-include], err: false
  ./fastdeploy_capi/vision/detection/contrib/yolo/model.h:20:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/vision/result.h [-Wmicrosoft-include], err: false
  ./fastdeploy_capi/vision/detection/contrib/yolo/model.h:21:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/vision/detection/contrib/yolo/base_define.h [-Wmicrosoft-include], err: false
  ./fastdeploy_capi/vision.h:22:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/vision/ocr/ppocr/model.h [-Wmicrosoft-include], err: false
  ./fastdeploy_capi/vision/ocr/ppocr/model.h:17:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/core/fd_common.h [-Wmicrosoft-include], err: false
  ./fastdeploy_capi/vision/ocr/ppocr/model.h:18:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/core/fd_type.h [-Wmicrosoft-include], err: false
  ./fastdeploy_capi/vision/ocr/ppocr/model.h:19:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/runtime/runtime_option.h [-Wmicrosoft-include], err: false
  ./fastdeploy_capi/vision/ocr/ppocr/model.h:20:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/vision/result.h [-Wmicrosoft-include], err: false
  ./fastdeploy_capi/vision/ocr/ppocr/model.h:21:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/vision/ocr/ppocr/base_define.h [-Wmicrosoft-include], err: false
  ./fastdeploy_capi/vision.h:23:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/vision/segmentation/ppseg/model.h [-Wmicrosoft-include], err: false
  ./fastdeploy_capi/vision/segmentation/ppseg/model.h:17:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/core/fd_common.h [-Wmicrosoft-include], err: false
  ./fastdeploy_capi/vision/segmentation/ppseg/model.h:18:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/core/fd_type.h [-Wmicrosoft-include], err: false
  ./fastdeploy_capi/vision/segmentation/ppseg/model.h:19:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/runtime/runtime_option.h [-Wmicrosoft-include], err: false
  ./fastdeploy_capi/vision/segmentation/ppseg/model.h:20:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/vision/result.h [-Wmicrosoft-include], err: false
  ./fastdeploy_capi/vision.h:24:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/vision/result.h [-Wmicrosoft-include], err: false
  ./fastdeploy_capi/vision.h:25:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/vision/visualize.h [-Wmicrosoft-include], err: false
  ./fastdeploy_capi/vision/visualize.h:17:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/core/fd_common.h [-Wmicrosoft-include], err: false
  ./fastdeploy_capi/vision/visualize.h:18:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/core/fd_type.h [-Wmicrosoft-include], err: false
  ./fastdeploy_capi/vision/visualize.h:19:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/vision/result.h [-Wmicrosoft-include], err: false
  ./fastdeploy_capi/vision.h:28:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/core/fd_type.h [-Wmicrosoft-include], err: false
  ./fastdeploy_capi/vision.h:29:10: warning: #include resolved using non-portable Microsoft search rules as: ./fastdeploy_capi/runtime/runtime_option.h [-Wmicrosoft-include], err: false
  thread 'main' panicked at 'Unable to generate bindings: ()', build.rs:20:10
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library\std\src\panicking.rs:593
     1: core::panicking::panic_fmt
               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library\core\src\panicking.rs:67
     2: core::result::unwrap_failed
               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library\core\src\result.rs:1651
     3: core::result::Result<T,E>::expect
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.



```

@wanziyu

**Comment by chaosgoo** [comment]
今天我在bindgen elk时遇到了类似的错误,碰巧就找到了这里.
至于elk那边的报错已经通过简单的将<>引入头文件改成了""引入头文件解决了,然后就想看看你这里是不是同样的原因所致.
摸索一番以后发现比我那里的报错多多了,不过最终还是成功cargo build出来了.
跟随README中的指引,成功执行了
```bash
./target/debug/infer.exe --model yolov8s.onnx --image 000000014439.jpg --device 0
```

你可以试着把wrapper.h里面的
```c
#include <fastdeploy_capi/vision.h>
```
修改为
```c
#include "fastdeploy_capi/vision.h"
```
此时应该会遇到新的错误,比如头文件找不到之类的.

我就遇到了stdio.h和stdint.h找不到的问题.
非常奇怪的是上面提到的elk项目就完全没有这个问题,于是我拙劣地手动指向这两个头文件的位置
```rust
    let bindings = bindgen::Builder::default()
        .header("wrapper.h")
        .clang_arg(format!("-I{}", r"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\include")) // stdint.h.
        .clang_arg(format!("-I{}", r"C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\ucrt"))// stdio.h.
        .parse_callbacks(Box::new(bindgen::CargoCallbacks))
        .generate()
        .expect("Unable to generate bindings");
```
这是我当前的build.rs内容
```rust
use std::env;
use std::path::PathBuf;

extern crate cc;

fn main() {
    println!("cargo:rustc-link-search=native=fastdeploy_capi");
    println!("cargo:rerun-if-changed=wrapper.h");
    let bindings = bindgen::Builder::default()
        .header("wrapper.h")
        .clang_arg(format!("-I{}", r"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\include")) // stdint not fount
        .clang_arg(format!("-I{}", r"C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\ucrt"))// stdio.h not found.
        .parse_callbacks(Box::new(bindgen::CargoCallbacks))
        .generate()
        .expect("Unable to generate bindings");
    let out_path = PathBuf::from(env::var("OUT_DIR").unwrap());
    bindings
        .write_to_file(out_path.join("bindings.rs"))
        .expect("Couldn't write bindings!");
}
```
这个是我的Cargo.toml内容,除此之外没有修改其他文件内容.
```toml
[package]
name = "elk-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"

[build-dependencies]
cc = "1.0"
bindgen = "0.66.1"
```
我yolov8文件夹下的内容长这样
```bash
.
├── 000000014439.jpg
├── Cargo.lock
├── Cargo.toml
├── README.md
├── README_CN.md
├── build.rs
├── core_tokenizers.dll
├── fastdeploy.dll
├── fastdeploy_capi
│   ├── core
│   ├── internal
│   ├── runtime
│   ├── vision
│   └── vision.h
├── icudt70.dll
├── icuuc70.dll
├── lib
│   ├── fastdeploy.dll
│   └── fastdeploy.lib
├── libhwloc-5.dll
├── libiomp5md.dll
├── mkldnn.dll
├── mklml.dll
├── onnxruntime.dll
├── onnxruntime_providers_shared.dll
├── opencv_ffmpeg3416_64.dll
├── opencv_world3416.dll
├── openvino.dll
├── openvino_auto_batch_plugin.dll
├── openvino_auto_plugin.dll
├── openvino_c.dll
├── openvino_gapi_preproc.dll
├── openvino_hetero_plugin.dll
├── openvino_intel_cpu_plugin.dll
├── openvino_intel_gpu_plugin.dll
├── openvino_ir_frontend.dll
├── openvino_onnx_frontend.dll
├── openvino_paddle_frontend.dll
├── openvino_tensorflow_fe.dll
├── paddle2onnx.dll
├── paddle_inference.dll
├── plugins.xml
├── src
│   └── main.rs
├── target
│   ├── CACHEDIR.TAG
│   └── debug
├── tbb.dll
├── tbb_preview.dll
├── tbbbind.dll
├── tbbmalloc.dll
├── vis_result_yolov8.jpg
├── wrapper.h
├── yaml-cpp.dll
└── yolov8s.onnx
```
多出来的这些dll是我下载[文档](https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/en/build_and_install/download_prebuilt_libraries.md)中的C++ SDK后得到的**fastdeploy_init.bat**自动复制出来的.

## 环境
系统:
Windows 11
LLVM:
LLVM.LLVM               16.0.6                   winget
cargo:
1.71.0 (cfd3bbd8f 2023-06-08)
