### ISSUE TITLE
visualdl启动后，打开页面报错

### ISSUE THREAD

**Issue by bltcn** [PaddlePaddle/FastDeploy#2174]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： docker paddlepaddle/fastdeploy:1.0.7-gpu-cuda11.6-trt8.5-22.12
- 【编译命令】docker paddlepaddle/fastdeploy:1.0.7-gpu-cuda11.6-trt8.5-22.12
- 【系统平台】: docker paddlepaddle/fastdeploy:1.0.7-gpu-cuda11.6-trt8.5-22.12
- 【硬件】： Nvidia GPU 3070
- 【编译语言】：python3.8
- visualdl 2.5.3
- 
## 问题日志及出现问题的操作流程
root@localhost:/FastDeploy/examples# visualdl --host 0.0.0.0 --port 8080
/usr/lib/python3/dist-packages/requests/init.py:89: RequestsDependencyWarning: urllib3 (2.0.2) or chardet (3.0.4) doesn't match a supported version!
warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
VisualDL 2.5.3
Running VisualDL at http://0.0.0.0:8080/ (Press CTRL+C to quit)
[ERROR 2023-08-20 02:55:12,738 lib.py:637] Unexpected error: <class 'AttributeError'>
'LogReader' object has no attribute '_model'
<traceback object at 0x7fd9ca415340>
[ERROR 2023-08-20 02:55:14,740 lib.py:637] Unexpected error: <class 'AttributeError'>
'LogReader' object has no attribute '_model'
<traceback object at 0x7fd9ca4150c0>
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/visualdl/server/lib.py", line 633, in retry
return function(*args, **kwargs)
File "/usr/local/lib/python3.8/dist-packages/visualdl/server/lib.py", line 585, in get_static_graph
if log_reader.model:
File "/usr/local/lib/python3.8/dist-packages/visualdl/reader/reader.py", line 100, in model
return self._model
AttributeError: 'LogReader' object has no attribute '_model'
[ERROR 2023-08-20 02:55:16,743 api.py:75] Internal server error. Retry later.
界面也不正常
![image](https://github.com/PaddlePaddle/FastDeploy/assets/7421901/f4160ae0-b677-450c-89bb-305615bad3b6)

**Comment by bltcn** [comment]
初步测试是2.5.3的错误，2.5.0没有这个问题
