### ISSUE TITLE
模型服务化部署了2个版本，调用历史版本报错

### ISSUE THREAD

**Issue by bbmeat** [PaddlePaddle/FastDeploy#2185]
*********************************************
## 环境

- 【FastDeploy版本】：[ 说明具体的版本，如fastdeploy-linux-gpu-0.8.0](fastdeploy:1.0.1-gpu-cuda11.4-trt8.4-21.10)
- 【编译命令】如果您是自行编译的FastDeploy，请说明您的编译方式（参数命令）
- 【系统平台】: Centos7.9
- 【硬件】： Nvidia GPU A16， CUDA 11.7
- 【编译语言】： Python3.8

-【服务化部署后调用报错】
模型部署文件目录
model_name  -  modele  -  frcnn - 1
                                                     - 2
                                                     - config.pbtxt
                                         - preprocess - 1 - infer_cfg.yml
                                                                   - model.py
                                                              - 2 - infet_cfg.yml
                                                                   - model.py
                                         - postprocess - 1 - model.py
                                                                - 2 - model.py
                                                                - config.pbtxt
                                         - runtime - 1 - model.pdiparams
                                                               - model.pdmodel
                                                         - 2 - model.pdiparams
                                                               - model.pdmodel
                                                         - config.pbtxt
 用grpc的客户端进行调用，如果frcnn中的config.pbtxt中的modelversion写-1的时候会直接调用最新的模型版本，如果我同时部署了1,2两个版本的模型，按照triton中说的版本控制进行的修改modelversion，改为1或者2则无法调用，docker会直接闪退。
报错如下
08/25/2023 17:27:37 - ERROR - uvicorn.error -   Exception in ASGI application
Traceback (most recent call last):
  File "/home/j/.virtualenvs/rt/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 376, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/j/.virtualenvs/rt/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/j/.virtualenvs/rt/lib/python3.8/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/home/j/.virtualenvs/rt/lib/python3.8/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/j/.virtualenvs/rt/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/j/.virtualenvs/rt/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/j/.virtualenvs/rt/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/j/.virtualenvs/rt/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/j/.virtualenvs/rt/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/j/.virtualenvs/rt/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/j/.virtualenvs/rt/lib/python3.8/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/j/.virtualenvs/rt/lib/python3.8/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/j/.virtualenvs/rt/lib/python3.8/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/j/.virtualenvs/rt/lib/python3.8/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/home/j/.virtualenvs/rt/lib/python3.8/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/j/.virtualenvs/rt/lib/python3.8/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/j/.virtualenvs/rt/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/j/.virtualenvs/rt/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/j/.virtualenvs/rt/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/liu/code/serving-online/mypaddledet_grpc_client_url.py", line 114, in infer_image
    infer_request = client_request(image_url, mission_name, version, draw_threshold)
  File "/home/liu/code/serving-online/mypaddledet_grpc_client_url.py", line 238, in client_request
    runner = SyncGRPCTritonRunner(model_url, model_type, model_version)
  File "/home/liu/code/serving-online/mypaddledet_grpc_client_url.py", line 46, in __init__
    error = self._verify_triton_state(self._client)
  File "/home/liu/code/serving-online/mypaddledet_grpc_client_url.py", line 96, in _verify_triton_state
    if not triton_client.is_server_live():
  File "/home/j/.virtualenvs/rt/lib/python3.8/site-packages/tritonclient/grpc/__init__.py", line 231, in is_server_live
    raise_error_grpc(rpc_error)
  File "/home/j/.virtualenvs/rt/lib/python3.8/site-packages/tritonclient/grpc/__init__.py", line 61, in raise_error_grpc
    raise get_error_grpc(rpc_error) from None
tritonclient.utils.InferenceServerException: [StatusCode.UNAVAILABLE] Broken pipe

**Comment by bbmeat** [comment]
我对照Triton，fastdeploy采用的是集成模型，感觉这个的版本控制不好搞，因为目标检测需要用到yml文件，如果改成platform模式有没有大佬可以给一个demo告诉我怎么改
