### ISSUE TITLE
web_demo 集成问题

### ISSUE THREAD

**Issue by effortcheep** [PaddlePaddle/FastDeploy#2227]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境
node 12.20.0

vue 2.5.3

使用 npm install @paddle-js-models/ocr  安装完成后 在页面调用
```js
<template>
  <div id="app">
  </div>
</template>

<script>
import * as ocr from '@paddle-js-models/ocr'

export default {
  name: 'App',
  mounted() {
    ocr.init()
  }
}
</script>

<style>
</style>
```

报错 
index.esm.js:404 Uncaught ReferenceError: Module is not defined
    at eval (index.esm.js:404:1)
    at eval (index.esm.js:401:1)
    at eval (index.esm.js:404:1)
    at createCommonjsModule (index.esm.js:395:1)
    at Object.eval (index.esm.js:398:1)
    at eval (index.esm.js:1095:30)
    at ./node_modules/@paddle-js-models/ocr/lib/index.esm.js (app.js:734:1)
    at __webpack_require__ (app.js:679:30)
    at fn (app.js:89:20)
    at eval (selector.js?type=script&index=0!./src/App.vue:2:80)

**Comment by FuriousSnail** [comment]
在vite-node中使用，遇到同样的问题。

**Comment by effortcheep** [comment]
demo里面 html 加了个  Module 的全局变量声明
服了这群人了

**Comment by muleoo** [comment]
> demo里面 html 加了个 Module 的全局变量声明 服了这群人了

确实，在这里  [<script>var Module;</script>](https://github.com/PaddlePaddle/FastDeploy/blob/cfebd24dfc593157a41c4b398afdc75ec7791aa6/examples/application/js/web_demo/src/pages/cv/ocr/TextRecognition/index.html#L4C31-L4C31)  
但是这么做是为了啥？也没见哪里去操作 Module

**Comment by mzzya** [comment]
![image](https://github.com/PaddlePaddle/FastDeploy/assets/19657992/8ff0ab48-33f9-46ce-9afb-08bea4b6c0e9)
