### ISSUE TITLE
FastDeploy initalized failed! Error: libiomp5.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by xiaomujiang** [PaddlePaddle/FastDeploy#2256]
## 环境

- 【FastDeploy版本 自己变异的
- https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/en/build_and_install/huawei_ascend.md
- 使用官方的docker 进行源码编译
- 【编译命令】
- 【系统平台】:  Linux 192.168.31.5 5.10.0-153.29.0.106.oe2203sp2.x86_64 #1 SMP Thu Oct 12 10:04:22 CST 2023 x86_64 x86_64 x86_64 GNU/Linux
- 【硬件】： ascend 310p
- 【编译语言】： C++ / Python(3.7或3.8等）
# Download the latest source code
git clone https://github.com/PaddlePaddle/FastDeploy.git
cd FastDeploy/python
export WITH_ASCEND=ON
export ENABLE_VISION=ON

python setup.py build
python setup.py bdist_wheel

## 问题日志及出现问题的操作流程,  fastdeploy导入失败
root@192:/Work/FastDeploy/python/dist# python -c "import fastdeploy"
Traceback (most recent call last):
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/fastdeploy_python-0.0.0-py3.7-linux-x86_64.egg/fastdeploy/c_lib_wrap.py", line 164, in <module>
    from .libs.fastdeploy_main import *
ImportError: libiomp5.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/fastdeploy_python-0.0.0-py3.7-linux-x86_64.egg/fastdeploy/__init__.py", line 122, in <module>
    from .c_lib_wrap import (
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/fastdeploy_python-0.0.0-py3.7-linux-x86_64.egg/fastdeploy/c_lib_wrap.py", line 166, in <module>
    raise RuntimeError(f"FastDeploy initalized failed! Error: {e}")
RuntimeError: FastDeploy initalized failed! Error: libiomp5.so: cannot open shared object file: No such file or directory

搜索libiomp5.so
/usr/local/python3.7.5/lib/python3.7/site-packages/fastdeploy_python-0.0.0-py3.7-linux-x86_64.egg/fastdeploy/libs/third_libs/paddlelite/lib/lib/libiomp5.so
/Work/python/fastdeploy/libs/third_libs/paddlelite/lib/libbak/libiomp5.so
/Work/python/fastdeploy/libs/third_libs/paddlelite/lib/lib/libiomp5.so
/Work/python/.setuptools-cmake-build/third_libs/install/paddlelite/lib/lib/libiomp5.so
/Work/FastDeploy/python/fastdeploy/libs/third_libs/paddlelite/lib/lib/libiomp5.so
/Work/FastDeploy/python/build/lib.linux-x86_64-cpython-37/fastdeploy/libs/third_libs/paddlelite/lib/lib/libiomp5.so
/Work/FastDeploy/python/build/lib.linux-x86_64-3.7/fastdeploy/libs/third_libs/paddlelite/lib/lib/libiomp5.so
/Work/FastDeploy/python/.setuptools-cmake-build/third_libs/install/paddlelite/lib/lib/libiomp5.so

**Comment by jiangjiajun** [comment]
export LD_LIBRARY_PATH试下解决

**Comment by Hakstar** [comment]
请问这个问题解决了吗？我也同样是310p的设备，无法import fastdeploy
