### ISSUE TITLE
rk3566 python 导入 fastdeploy 报错

### ISSUE THREAD

**Issue by gerhardt-1024** [PaddlePaddle/FastDeploy#2292]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： 说明具体的版本，如fastdeploy-linux-gpu-0.8.0
- 【编译命令】
export ENABLE_ORT_BACKEND=ON
export ENABLE_RKNPU2_BACKEND=ON
export ENABLE_VISION=ON
export RKNN2_TARGET_SOC=RK356X
python3 setup.py build -j3

python3 setup.py bdist_wheel
cd dist
pip3 install fastdeploy_python-0.0.0-cp38-cp38-linux_aarch64.whl
- 【系统平台】: Ubuntu 20.04
- 【硬件】：rk3566
- 【编译语言】： Python3.8

## 问题日志及出现问题的操作流程
- 附上详细的问题日志有助于快速定位分析
导入 fastdeploy 报错
 import fastdeploy
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/fastdeploy/c_lib_wrap.py", line 164, in <module>
    from .libs.fastdeploy_main import *
ImportError: /usr/local/lib/python3.8/dist-packages/fastdeploy/libs/libfastdeploy.so.0.0.0: undefined symbol: _ZN10fastdeploy8FDLogger14enable_warningE

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/fastdeploy/__init__.py", line 122, in <module>
    from .c_lib_wrap import (
  File "/usr/local/lib/python3.8/dist-packages/fastdeploy/c_lib_wrap.py", line 166, in <module>
    raise RuntimeError(f"FastDeploy initalized failed! Error: {e}")
RuntimeError: FastDeploy initalized failed! Error: /usr/local/lib/python3.8/dist-packages/fastdeploy/libs/libfastdeploy.so.0.0.0: undefined symbol: _ZN10fastdeploy8FDLogger14enable_warningE

**Comment by zhangjunhst** [comment]
我也需要相同的问题。请问有解决方法了吗？

**Comment by lsx66** [comment]
FastDeploy initalized failed! Error: /usr/local/lib/python3.8/dist-packages/fastdeploy/libs/libfastdeploy.so.0.0.0: undefined symbol: _ZN6paddle14AnalysisConfig20EnableTensorRtEngineEliiNS0_9PrecisionEbbb
同样的报错 怎么解决？
