### ISSUE TITLE
服务端部署PPYoloe模型，在执行客户端请求时，报错 tritonclient.utils.InferenceServerException: [StatusCode.UNAVAILABLE] Socket closed

### ISSUE THREAD

**Issue by huangjun11** [PaddlePaddle/FastDeploy#2299]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： paddlepaddle/fastdeploy:1.0.4-cpu-only-21.10
- 【编译命令】如果您是自行编译的FastDeploy，请说明您的编译方式（参数命令）
- 【系统平台】: Linux x64(Ubuntu 18.04) /
- 【硬件】： Nvidia GPU 2080TI， CUDA 11.4 CUDNN 8.3
- 【编译语言】：  Python(3.7或3.8等）

## 问题日志及出现问题的操作流程
- 附上详细的问题日志有助于快速定位分析
- 【模型跑不通】
- 执行examples中的paddledetection，能够成功启动服务
![图片](https://github.com/PaddlePaddle/FastDeploy/assets/86581237/227ca192-f01b-4280-ae1d-5f672f315f1b)
但是在执行客户端请求时python3 paddledet_grpc_client.py，出现如下错误。
tm: name: "INPUT"
datatype: "UINT8"
shape: -1
shape: -1
shape: -1
shape: 3

Traceback (most recent call last):
  File "/home/jsjx/junhuang/FastDeploy/examples/vision/detection/paddledetection/serving/paddledet_grpc_client.py", line 103, in <module>
    result = runner.Run([im, ])
  File "/home/jsjx/junhuang/FastDeploy/examples/vision/detection/paddledetection/serving/paddledet_grpc_client.py", line 73, in Run
    results = self._client.infer(
  File "/home/jsjx/anaconda3/envs/tuobao/lib/python3.9/site-packages/tritonclient/grpc/_client.py", line 1380, in infer
    raise_error_grpc(rpc_error)
  File "/home/jsjx/anaconda3/envs/tuobao/lib/python3.9/site-packages/tritonclient/grpc/_utils.py", line 77, in raise_error_grpc
    raise get_error_grpc(rpc_error) from None
此时，服务断也被终止
![图片](https://github.com/PaddlePaddle/FastDeploy/assets/86581237/d2de22f9-f447-4bb3-8dd8-12ebe4e5d3cb)

**Comment by rainyfly** [comment]
启动容器的时候指定--shm-size 把共享内存之类的设置大点呢
