### ISSUE TITLE
libopencv_flann.so.3.4: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/FastDeploy#2376]
开发板: Orange Pi AIpro
编译方式: 源码编译
python 3.9
ubuntu 22.0

 ```python
git clone https://github.com/PaddlePaddle/FastDeploy.git
cd FastDeploy/python
export WITH_ASCEND=ON
export ENABLE_VISION=ON

python setup.py build
python setup.py bdist_wheel
```

```python
ython infer.py --model yolov5s_infer --image 000000014439.jpg --device ascend
Traceback (most recent call last):
  File "/home/HwHiAiUser/.conda/envs/FastDeploy/lib/python3.8/site-packages/fastdeploy/c_lib_wrap.py", line 164, in <module>
    from .libs.fastdeploy_main import *
ImportError: libopencv_flann.so.3.4: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "infer.py", line 1, in <module>
    import fastdeploy as fd
  File "/home/HwHiAiUser/.conda/envs/FastDeploy/lib/python3.8/site-packages/fastdeploy/__init__.py", line 122, in <module>
    from .c_lib_wrap import (
  File "/home/HwHiAiUser/.conda/envs/FastDeploy/lib/python3.8/site-packages/fastdeploy/c_lib_wrap.py", line 166, in <module>
    raise RuntimeError(f"FastDeploy initalized failed! Error: {e}")
RuntimeError: FastDeploy initalized failed! Error: libopencv_flann.so.3.4: cannot open shared object file: No such file or directory

```

如何指定FastDeploy默认安装的opencv目录

怀疑系统环境没有权限，所以没有加上

应该要怎么弄

**Comment by heliqi** [comment]
python版本吗？ 有安装opencv吗？ pip install opencv-python
注意ubuntu也需要apt-get install  libopencv-dev 安装opencv(也可以网上搜下opencv安装)

**Comment by monkeycc** [comment]
```
pkg-config --modversion opencv
4.0.1
```
ubuntu安装后 显示出opencv了

```
pip uninstall opencv-python
pip install opencv-python
```
python环境中 也重新安装了

问题依旧 @heliqi

**Comment by jiangjiajun** [comment]
试下找到这个so所在的安装路径，export LD_LIBRARY_PATH看下

**Comment by heliqi** [comment]
find / -name "libopencv_flann.so" 全局搜下so看看， 如果没有可能ubuntu漏装了opencv的依赖库；
如果存在就 export LD_LIBRARY_PATH=xxx:$LD_LIBRARY_PATH 把找到的路径加入环境变量

**Comment by 15380831711** [comment]
尝试安装3.x.x版本的opencv，或者源码编译，试了下opencv-3.4.16版本，解决了。
