### ISSUE TITLE
Building in Jetson Agx is failing while running setup.py

### ISSUE THREAD

**Issue by csoham96** [PaddlePaddle/FastDeploy#2382]
## Environment

FastDeploy version: develop branch
OS Platform: e.g. Linux aarch64 (jetson)
Hardware: e.g. Nvidia Jetson AGX
Program Language: e.g. Python 3.8

## Problem description
running build
running build_py
running create_version
running cmake_build
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Downloading file from https://bj.bcebos.com/fastdeploy/third_libs/patchelf-0.15.0-aarch64.tar.gz to /home/jetson-agx/FastDeploy/python/.setuptools-cmake-build/patchelf-0.15.0-aarch64.tar.gz ...
-- [download 1% complete]
-- [download 6% complete]
-- [download 11% complete]
-- [download 16% complete]
-- [download 21% complete]
-- [download 27% complete]
-- [download 32% complete]
-- [download 37% complete]
-- [download 42% complete]
-- [download 47% complete]
-- [download 52% complete]
-- [download 57% complete]
-- [download 63% complete]
-- [download 68% complete]
-- [download 73% complete]
-- [download 78% complete]
-- [download 83% complete]
-- [download 88% complete]
-- [download 93% complete]
-- [download 99% complete]
-- [download 100% complete]
Decompress file /home/jetson-agx/FastDeploy/python/.setuptools-cmake-build/patchelf-0.15.0-aarch64.tar.gz ...
-- Use the default onnxruntime lib. The ONNXRuntime path: /home/jetson-agx/FastDeploy/python/.setuptools-cmake-build/third_libs/install/onnxruntime
Cannot compile with onnxruntime-gpu while in linux-aarch64 platform, fallback to onnxruntime-cpu
-- Found Python: /usr/bin/python2.7 (found version "2.7.18") found components: Interpreter Development 
-- Copying /Download/paddle_inference_jetson to /home/jetson-agx/FastDeploy/python/.setuptools-cmake-build/third_libs/install/paddle_inference ...
cp: cannot stat '/Download/paddle_inference_jetson': No such file or directory
CMake Error at cmake/paddle_inference.cmake:272 (string):
  string sub-command REGEX, mode MATCH needs at least 5 arguments total to
  command.
Call Stack (most recent call first):
  CMakeLists.txt:245 (include)

CMake Error at cmake/paddle_inference.cmake:273 (string):
  string sub-command REGEX, mode MATCH needs at least 5 arguments total to
  command.
Call Stack (most recent call first):
  CMakeLists.txt:245 (include)

CMake Error at cmake/paddle_inference.cmake:274 (string):
  string sub-command REGEX, mode MATCH needs at least 5 arguments total to
  command.
Call Stack (most recent call first):
  CMakeLists.txt:245 (include)

-- The CUDA compiler identification is NVIDIA 11.4.239
-- Check for working CUDA compiler: /usr/local/cuda-11.4/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda-11.4/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- CUDA compiler: /usr/local/cuda-11.4/bin/nvcc, version: NVIDIA 11.4.239
-- CUDA detected: 11.4.239
-- NVCC_FLAGS_EXTRA:  -gencode arch=compute_86,code=sm_86
-- Use the opencv lib specified by user. The OpenCV path: /usr/lib/aarch64-linux-gnu/cmake/opencv4/
-- Found OpenCV: /usr (found version "4.5.4") 
-- 
-- *************FastDeploy Building Summary**********
--   CMake version             : 3.16.3
--   CMake command             : /usr/bin/cmake
--   System                    : Linux
--   C++ compiler              : /usr/bin/c++
--   C++ standard              : 11
--   C++ cuda standard         : 11
--   C++ compiler version      : 9.4.0
--   CXX flags                 : -Wno-format -g0 -O3
--   EXE linker flags          : 
--   Shared linker flags       : 
--   Build type                : Release
--   Compile definitions       : _GLIBCXX_USE_CXX11_ABI=1;FASTDEPLOY_LIB;CMAKE_BUILD_TYPE=Release;ENABLE_ORT_BACKEND;ENABLE_PADDLE_BACKEND;WITH_GPU;ENABLE_TRT_BACKEND;ENABLE_VISION;ENABLE_PADDLE2ONNX
--   CMAKE_PREFIX_PATH         : 
--   CMAKE_INSTALL_PREFIX      : /usr/local
--   CMAKE_MODULE_PATH         : 
-- 
--   FastDeploy version        : 0.0.0
--   ENABLE_ORT_BACKEND        : ON
--   ENABLE_RKNPU2_BACKEND     : OFF
--   ENABLE_HORIZON_BACKEND    : OFF
--   ENABLE_SOPHGO_BACKEND     : OFF
--   ENABLE_PADDLE_BACKEND     : ON
--   ENABLE_LITE_BACKEND       : OFF
--   ENABLE_POROS_BACKEND      : OFF
--   ENABLE_TRT_BACKEND        : ON
--   ENABLE_OPENVINO_BACKEND   : OFF
--   ENABLE_TVM_BACKEND        : OFF
--   ENABLE_BENCHMARK          : OFF
--   ENABLE_VISION             : ON
--   ENABLE_TEXT               : OFF
--   ENABLE_ENCRYPTION         : OFF
--   ENABLE_FLYCV              : OFF
--   ENABLE_CVCUDA             : OFF
--   WITH_GPU                  : ON
--   WITH_IPU                  : OFF
--   WITH_OPENCL               : OFF
--   WITH_TESTING              : OFF
--   WITH_ASCEND               : OFF
--   WITH_DIRECTML             : OFF
--   WITH_TIMVX                : OFF
--   WITH_KUNLUNXIN            : OFF
--   WITH_CAPI                 : OFF
--   WITH_CSHARPAPI            : OFF
--   ONNXRuntime version       : 1.12.0
--   Paddle Inference version  : 
--   PADDLE_WITH_ENCRYPT       : OFF
--   PADDLE_WITH_AUTH          : OFF
--   CUDA_DIRECTORY            : /usr/local/cuda
--   TRT_DRECTORY              : /home/jetson-agx/FastDeploy/python/.setuptools-cmake-build/UNDEFINED
--   Python executable         : /usr/bin/python3
--   Python includes           : /usr/include/python3.8
-- Found PythonInterp: /usr/bin/python3 (found version "3.8.10") 
-- Found PythonLibs: /usr/lib/aarch64-linux-gnu/libpython3.8.so (found version "3.8.10") 
-- Configuring incomplete, errors occurred!
See also "/home/jetson-agx/FastDeploy/python/.setuptools-cmake-build/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "setup.py", line 445, in <module>
    setuptools.setup(
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 308, in run
    self.run_command('cmake_build')
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 294, in run
    subprocess.check_call(cmake_args)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/cmake', '-DPYTHON_INCLUDE_DIR=/usr/include/python3.8', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-DBUILD_FASTDEPLOY_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=paddle2onnx', '-DPY_EXT_SUFFIX=.cpython-38-aarch64-linux-gnu.so', '-DCMAKE_BUILD_TYPE=Release', '-DLIBRARY_NAME=fastdeploy', '-DPY_LIBRARY_NAME=fastdeploy_main', '-DENABLE_TVM_BACKEND=OFF', '-DENABLE_RKNPU2_BACKEND=OFF', '-DENABLE_SOPHGO_BACKEND=OFF', '-DENABLE_ORT_BACKEND=OFF', '-DENABLE_OPENVINO_BACKEND=OFF', '-DENABLE_PADDLE_BACKEND=ON', '-DENABLE_POROS_BACKEND=OFF', '-DENABLE_TRT_BACKEND=OFF', '-DENABLE_LITE_BACKEND=OFF', '-DENABLE_VISION=ON', '-DENABLE_ENCRYPTION=OFF', '-DENABLE_FLYCV=OFF', '-DENABLE_CVCUDA=OFF', '-DENABLE_TEXT=OFF', '-DENABLE_BENCHMARK=OFF', '-DWITH_GPU=OFF', '-DWITH_IPU=OFF', '-DWITH_OPENCL=OFF', '-DWITH_TIMVX=OFF', '-DWITH_DIRECTML=OFF', '-DWITH_ASCEND=OFF', '-DWITH_KUNLUNXIN=OFF', '-DRKNN2_TARGET_SOC=', '-DTRT_DIRECTORY=UNDEFINED', '-DCUDA_DIRECTORY=/usr/local/cuda', '-DOPENCV_DIRECTORY=', '-DORT_DIRECTORY=', '-DPADDLEINFERENCE_DIRECTORY=/Download/paddle_inference_jetson', '-DPADDLEINFERENCE_VERSION=', '-DPADDLEINFERENCE_URL=', '-DPADDLEINFERENCE_API_COMPAT_2_4_x=OFF', '-DPADDLEINFERENCE_API_COMPAT_2_5_x=OFF', '-DPADDLEINFERENCE_API_COMPAT_DEV=OFF', '-DPADDLEINFERENCE_API_CUSTOM_OP=OFF', '-DPADDLE2ONNX_URL=', '-DPADDLELITE_URL=', '-DBUILD_ON_JETSON=ON', '-DBUILD_PADDLE2ONNX=OFF', '/home/jetson-agx/FastDeploy']' returned non-zero exit status 1.

**Comment by heliqi** [comment]
你使用的最新paddle？

**Comment by csoham96** [comment]
> 你使用的最新paddle？

I am using the devolpment branch

**Comment by jiangjiajun** [comment]
试下编译时，不集成Paddle后端呢

**Comment by heliqi** [comment]
> > 你使用的最新paddle？
> 
> I am using the devolpment branch

@csoham96  你可以回退下paddle版本，比如用2.3版本试试

**Comment by csoham96** [comment]
> 你可以回退下paddle版本，比如用2.3版本试试

Ok sure will try with 2.3version
