### ISSUE TITLE
How to load Adaface model if I only have pdparams?

### ISSUE THREAD

**Issue by angelabr** [PaddlePaddle/FastDeploy#2401]
Basically what the title says, I only have .pdparams and also a .yaml, but the tutorial shows that you meed both .pdiparams and .pdmodel for it to work. Any way to work just with .pdparams?

**Comment by juncaipeng** [comment]
You should use the pdparams files to export the inference model (pdmodel and pdiparams)

**Comment by angelabr** [comment]
I'm trying to do: 

```
export PADDLE_NNODES=1
export PADDLE_MASTER="127.0.0.1:12538"
export CUDA_VISIBLE_DEVICES=0
python -m paddle.distributed.launch \
    --nnodes=$PADDLE_NNODES \
    --master=$PADDLE_MASTER \
    --devices=$CUDA_VISIBLE_DEVICES \
    plsc-export \
    -c ./configs/IResNet100_WebFace42M_CosFace_pfc02_1n8c_dp_mp_fp16o1.yaml \
    -o Global.pretrained_model=/home/angela/Descargas/IResNet100_WebFace42M_CosFace_pfc02_1n8c_dp_mp_fp16o1 \
    -o FP16.level=O0 \
    -o Model.data_format=NCHW
```

and I get this error:

```
LAUNCH INFO 2024-03-11 12:29:45,551 ------------------------- ERROR LOG DETAIL -------------------------
Traceback (most recent call last):
  File "/home/angela/Descargas/PLSC-master/ven/bin/plsc-export", line 26, in <module>
    sys.exit(main())
  File "/home/angela/Descargas/PLSC-master/ven/bin/plsc-export", line 19, in main
    engine = Engine(config, mode="export")
  File "/home/angela/Descargas/PLSC-master/ven/lib/python3.7/site-packages/plsc/engine/engine.py", line 98, in __init__
    paddle.set_flags(RELATED_FLAGS_SETTING)
  File "/home/angela/Descargas/PLSC-master/ven/lib/python3.7/site-packages/paddle/fluid/framework.py", line 7493, in set_flags
    "Flag %s cannot set its value through this function." % (key)
ValueError: Flag FLAGS_cudnn_exhaustive_search cannot set its value through this function.
```
