### ISSUE TITLE
fastdeploy编译问题：1.用预编译的提示RuntimeOption不存在。2.自己编译，编译成功了安装失败。提示不支持当前平台 #11905

### ISSUE THREAD

**Issue by coding-jimmy** [PaddlePaddle/FastDeploy#2428]
问题1：用预编译的提示RuntimeOption不存在
 通过如下命令安装的预编译版本.提示RuntimeOption不存在
```sh
pip install fastdeploy-python -f https://www.paddlepaddle.org.cn/whl/fastdeploy.html
```
出错信息：
```python git:(main) ✗ python infer.py --det_model ch_PP-OCRv3_det_infer --cls_model ch_ppocr_mobile_v2.0_cls_infer --rec_model ch_PP-OCRv3_rec_infer --rec_label_file ppocr_keys_v1.txt --image 12.jpg --device cpu --backend paddle

fd <module 'fastdeploy' (namespace)>
Traceback (most recent call last):
  File "/Users/leo/PaddleOCR/deploy/fastdeploy/cpu-gpu/python/infer.py", line 185, in <module>
    det_option, cls_option, rec_option = build_option(args)
  File "/Users/che3vinci/PaddleOCR/deploy/fastdeploy/cpu-gpu/python/infer.py", line 75, in build_option
    det_option = fd.RuntimeOption()
AttributeError: module 'fastdeploy' has no attribute 'RuntimeOption'

```

问题2：2.自己编译，编译成功了安装失败。提示不支持当前平台
- 【编译命令】如果您是自行编译的FastDeploy，请说明您的编译方式（参数命令）
- 【系统平台】: Mac OSX intel(14.4.1) X86-64
- 【硬件】： CPU
- 【编译语言】：  Python 3.9
- 编译方法：

```sh
git clone https://github.com/PaddlePaddle/FastDeploy.git
cd FastDeploy/python
export ENABLE_PADDLE_BACKEND=ON
export ENABLE_OPENVINO_BACKEND=ON

python setup.py build
python setup.py bdist_wheel
```
编译完成后，安装过程中提示错误
```sh
ERROR: fastdeploy_python-0.0.0-cp39-cp39-macosx_12_0_x86_64.whl is not a supported wheel on this platform.

```

意思是说不支持我现在的osx 14 系统吗？只支持osx12的？

**Comment by juncaipeng** [comment]
是的，可以参考log给出的error提示。

**Comment by ChaoII** [comment]
把wheel包的名字改一下就好了12_0给它改了
