### ISSUE TITLE
module 'fastdeploy' has no attribute 'RuntimeOption'

### ISSUE THREAD

**Issue by GaoYuelong** [PaddlePaddle/FastDeploy#2436]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： fast-tokenizer-python 1.0.2

通过如下命令安装的.提示RuntimeOption不存在

pip install fastdeploy-python -f https://www.paddlepaddle.org.cn/whl/fastdeploy.html
出错信息：

```
fd <module 'fastdeploy' (namespace)>
Traceback (most recent call last):
  File "/Users/che3vinci/PaddleOCR/deploy/fastdeploy/cpu-gpu/python/infer.py", line 185, in <module>
    det_option, cls_option, rec_option = build_option(args)
  File "/Users/che3vinci/PaddleOCR/deploy/fastdeploy/cpu-gpu/python/infer.py", line 75, in build_option
    det_option = fd.RuntimeOption()
AttributeError: module 'fastdeploy' has no attribute 'RuntimeOption'
```

**Comment by Jiang-Jia-Jun** [comment]
确保当前目录下，没有命名为fastdeploy的代码文件或目录

**Comment by will-bug** [comment]
同样出现了这个问题, 当前代码并没有出现同名文件

**Comment by jackyzzy** [comment]
我的CPU环境没问题，GPU出现同样的问题，还没解决。
