### ISSUE TITLE
使用官方文字cls模型转onnx正常再转rknn报错

### ISSUE THREAD

**Issue by Zomcxj** [PaddlePaddle/FastDeploy#2567]
- 【系统平台】: Linux x64(Ubuntu 18.04) 
- 【编译语言】：Python(3.6）

python export.py --config_path config/ppocrv3_cls.yaml --target_platform rk3588 
{'mean': [[127.5, 127.5, 127.5]], 'std': [[127.5, 127.5, 127.5]], 'model_path': './onnx/ch_ppocr_mobile_v2.0_cls_infer.onnx', 'outputs_nodes': None, 'do_quantization': False, 'dataset': None, 'output_folder': './ch_ppocr_mobile_v2.0_cls_infer'}
W __init__: rknn-toolkit2 version: 1.5.0+1fa95b5c
E load_onnx: Catch exception when loading onnx model: /home/cxj/cxj/CPP/PPOCR/Base/rockchip/rknpu2_tools/onnx/ch_ppocr_mobile_v2.0_cls_infer.onnx!
E load_onnx: Traceback (most recent call last):
E load_onnx:   File "rknn/api/rknn_base.py", line 1382, in rknn.api.rknn_base.RKNNBase.load_onnx
E load_onnx:   File "rknn/api/rknn_base.py", line 658, in rknn.api.rknn_base.RKNNBase._create_ir_and_inputs_meta
E load_onnx:   File "rknn/api/ir_graph.py", line 58, in rknn.api.ir_graph.IRGraph.__init__
E load_onnx:   File "rknn/api/ir_graph.py", line 503, in rknn.api.ir_graph.IRGraph.rebuild
E load_onnx:   File "/home/cxj/anaconda3/envs/rknn/lib/python3.6/site-packages/onnx/checker.py", line 106, in check_model
E load_onnx:     C.check_model(protobuf_string)
E load_onnx: onnx.onnx_cpp2py_export.checker.ValidationError: Field 'shape' of type is required but missing.
W If you can't handle this error, please try updating to the latest version of the toolkit2 and runtime from:
  https://eyun.baidu.com/s/3eTDMk6Y (Pwd: rknn)  Path: RK_NPU_SDK / RK_NPU_SDK_1.X.0 / develop /
  If the error still exists in the latest version, please collect the corresponding error logs and the model,
  convert script, and input data that can reproduce the problem, and then submit an issue on:
  https://redmine.rock-chips.com (Please consult our sales or FAE for the redmine account)
Traceback (most recent call last):
  File "export.py", line 52, in <module>
    assert ret == 0, "Load model failed!"
AssertionError: Load model failed!

**Comment by Zomcxj** [comment]
使用Paddle2ONNX\tools\onnx\onnx_infer_shape.py即可解决报错

**Comment by x53151231** [comment]
> 使用Paddle2ONNX\tools\onnx\onnx_infer_shape.py即可解决报错

请问Paddle2ONNX\tools\onnx\onnx_infer_shape.py在哪里呢，没找到

**Comment by x53151231** [comment]
我也也到了同样的问题，请问如何解决的？

**Comment by Zomcxj** [comment]
> 我也也到了同样的问题，请问如何解决的？
https://github.com/PaddlePaddle/Paddle2ONNX/tree/develop/tools/onnx

**Comment by x53151231** [comment]
> > 我也也到了同样的问题，请问如何解决的？
> > https://github.com/PaddlePaddle/Paddle2ONNX/tree/develop/tools/onnx

问题已解决，非常感谢
