### ISSUE TITLE
windows10上开发，采用genymotion模拟器，用的easyedge arm sdk，调用sdk报错。

### ISSUE THREAD

**Issue by vsharer** [PaddlePaddle/FastDeploy#407]
错误信息：
],nativeLibraryDirectories=[/data/app/xxx.xxx-xxxx-Zr9QUg==/lib/x86, /system/lib, /system/vendor/lib]]] couldn't find "libedge-infer.so" .安装了Genymotion-ARM-Translation_for_9.0也不行

**Comment by vsharer** [comment]
完整的错误信息：
 Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/xxxxxxxxx==/base.apk"],nativeLibraryDirectories=[/data/app/xxxxx==/lib/x86, /system/lib, /system/vendor/lib]]] couldn't find "libedge-infer.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
        at java.lang.System.loadLibrary(System.java:1657)
        at com.baidu.ai.edge.core.infer.InferLiteJni.a(Unknown Source:21)
        at com.baidu.ai.edge.core.infer.InferManager.e(Unknown Source:13)?
        at com.baidu.ai.edge.core.base.BaseManager.<init>(Unknown Source:86)?
        at com.baidu.ai.edge.core.infer.InferManager.<init>(Unknown Source:5)?

**Comment by jiangjiajun** [comment]
Hi，你部署的是什么模型

**Comment by vsharer** [comment]
ocr模型，就是这个sdk:EasyEdge-Android-paddle-ocr-arm-SDK

**Comment by DefTruth** [comment]
目前还不支持x86架构，您可以先尝试下真机调试，现在支持arm64-v8a和armeabi-v7a这两种常见的架构

**Comment by vsharer** [comment]
谢谢
