### ISSUE TITLE
NameError: name 'ModelFormat' is not defined 

### ISSUE THREAD

**Issue by HiaHong** [PaddlePaddle/FastDeploy#738]
## Environment

FastDeploy version: e.g 0.8.0 or the latest code in develop branch
OS Platform: e.g. Linux x64 / Windows x64 / Mac OSX 12.1(arm or intel)
Hardware: e.g. Nvidia GPU 3060  CUDA 11.2 CUDNN 8.3
Program Language: e.g. Python 3.7

## Problem description
Please attach the log file if there's problem happend.
```
import fastdeploy

model = fastdeploy.vision.classification.YOLOv5Cls(r"D:\AHONG_Space\AHONG\mytools\best.onnx", params_file=None, runtime_option=None, model_format=ModelFormat.ONNX)

model.predict(r'D:\yolov5-master_v7.0\cash_fenlei\val\cash_you\ALN_cash_cash_2_3.jpg', topk=4)
```

bug:
```
[FastDeploy][INFO]:  Successfully found CUDA ToolKit from system PATH env -> C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin
Traceback (most recent call last):
  File "d:/AHONG_Space/AHONG/mytools/Fastdeply_yolov5_cla.py", line 20, in <module>
    model = fastdeploy.vision.classification.YOLOv5Cls(r"D:\AHONG_Space\AHONG\mytools\best.onnx", params_file=None, runtime_option=None, model_format=ModelFormat.ONNX)
NameError: name 'ModelFormat' is not defined
```

**Comment by jiangjiajun** [comment]
`ModelFormat` is a attribute of `fastdeploy`, using the following code
```
import fastdeploy
from fastdeploy import ModelFormat
model = fastdeploy.vision.classification.YOLOv5Cls(r"D:\AHONG_Space\AHONG\mytools\best.onnx", params_file=None, runtime_option=None, model_format=ModelFormat.ONNX)
```

**Comment by HiaHong** [comment]
> `ModelFormat`是的属性，使用以下代码`fastdeploy`
> 
> ```
> import fastdeploy
> from fastdeploy import ModelFormat
> model = fastdeploy.vision.classification.YOLOv5Cls(r"D:\AHONG_Space\AHONG\mytools\best.onnx", params_file=None, runtime_option=None, model_format=ModelFormat.ONNX)
> ```


感谢,增加了from fastdeploy import ModelFormat 之后,发现报另外的错
```
[FastDeploy][INFO]:  Successfully found CUDA ToolKit from system PATH env -> C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin
Traceback (most recent call last):
  File "d:/AHONG_Space/AHONG/mytools/Fastdeply_yolov5_cla copy.py", line 4, in <module>
    model = fastdeploy.vision.classification.YOLOv5Cls(r"D:\AHONG_Space\AHONG\mytools\best.onnx", params_file=None, runtime_option=None, model_format=ModelFormat.ONNX)
  File "D:\anaconda3\envs\paddleX\lib\site-packages\fastdeploy\vision\classification\contrib\yolov5cls.py", line 39, in __init__
    model_file, params_file, self._runtime_option, model_format)
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. fastdeploy.libs.fastdeploy_main.vision.classification.YOLOv5Cls(arg0: str, arg1: str, arg2: fastdeploy.libs.fastdeploy_main.RuntimeOption, arg3: fastdeploy.libs.fastdeploy_main.ModelFormat)

Invoked with: 'D:\\AHONG_Space\\AHONG\\mytools\\best.onnx', None, <repr raised Error>, <ModelFormat.ONNX: 2>
```

**Comment by jiangjiajun** [comment]
代码改为
```
import fastdeploy
from fastdeploy import ModelFormat
model = fastdeploy.vision.classification.YOLOv5Cls(r"D:\AHONG_Space\AHONG\mytools\best.onnx",  runtime_option=None, model_format=ModelFormat.ONNX)
```

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
